import type {
  ExerciseBiomechanics,
  BiomechanicalCheckpoint,
  MovementPhase,
} from "../../types";

const badmintonSmashCheckpoints: BiomechanicalCheckpoint[] = [
  {
    id: "smash-shoulder-er",
    name: "Shoulder external rotation at racket drop",
    description: "Extreme external rotation of the dominant shoulder at the base of the backswing, generating elastic energy for the throw-like smash motion",
    angle: { joint: "rightShoulder", p1: "rightElbow", p2: "rightShoulder", p3: "rightHip" },
    goodRange: [120, 150],
    warningRange: [100, 120],
    criticalRange: [0, 100],
    side: "right",
    phase: "Racket drop",
    weight: 0.9,
    cueGood: "Deep external rotation — elastic load stored",
    cueWarning: "Partial drop — losing racket head speed",
    cueCritical: "High elbow, no drop — arming the smash",
  },
  {
    id: "smash-elbow-extension",
    name: "Elbow extension velocity at contact",
    description: "Near-full elbow extension at the moment of contact for maximum linear reach and power transfer",
    angle: { joint: "rightElbow", p1: "rightShoulder", p2: "rightElbow", p3: "rightWrist" },
    goodRange: [170, 180],
    warningRange: [155, 170],
    criticalRange: [0, 155],
    side: "right",
    phase: "Contact",
    weight: 0.95,
    cueGood: "Snap locked — full whip at contact",
    cueWarning: "Partial extension — losing reach and pace",
    cueCritical: "Elbow bent — major power leak",
  },
  {
    id: "smash-wrist-snap",
    name: "Wrist flexion at contact (snap)",
    description: "Rapid wrist flexion and pronation at contact generating the steep downward angle of the smash",
    angle: { joint: "rightWrist", p1: "rightElbow", p2: "rightWrist", p3: "rightHand" },
    goodRange: [30, 60],
    warningRange: [15, 30],
    criticalRange: [0, 15],
    side: "right",
    phase: "Contact",
    weight: 0.85,
    cueGood: "Wrist snapped — shuttle driven steeply down",
    cueWarning: "Mild snap — losing angle and speed",
    cueCritical: "No wrist action — flat, slow smash",
  },
  {
    id: "smash-scissor-kick",
    name: "Scissor kick position — hip angle between legs",
    description: "Hip angle between lead and trail legs during the scissor kick creating body extension and torque through the air",
    angle: { joint: "leftHip", p1: "leftKnee", p2: "leftHip", p3: "rightHip" },
    goodRange: [120, 150],
    warningRange: [100, 120],
    criticalRange: [0, 100],
    side: "both",
    phase: "Jump/Scissor kick",
    weight: 0.7,
    cueGood: "Scissor wide — full body extension in air",
    cueWarning: "Legs together — losing air torque",
    cueCritical: "No kick — ground-bound smash",
  },
  {
    id: "smash-non-racket-arm",
    name: "Non-racket arm position pointing at shuttle",
    description: "Non-dominant arm extended upward tracking the shuttle, providing balance and shoulder elevation",
    angle: { joint: "leftShoulder", p1: "leftElbow", p2: "leftShoulder", p3: "rightShoulder" },
    goodRange: [140, 180],
    warningRange: [100, 140],
    criticalRange: [0, 100],
    side: "left",
    phase: "Acceleration",
    weight: 0.6,
    cueGood: "Pointing at shuttle — balanced and tracking",
    cueWarning: "Arm dropping — losing shoulder height",
    cueCritical: "Arm down — unbalanced, reduced reach",
  },
  {
    id: "smash-contact-height",
    name: "Contact height — maximum reach",
    description: "Full vertical extension of the racket arm at the highest possible contact point for steepest smash angle",
    angle: { joint: "rightArm", p1: "rightShoulder", p2: "rightWrist", p3: "rightHip" },
    goodRange: [175, 185],
    warningRange: [160, 175],
    criticalRange: [0, 160],
    side: "right",
    phase: "Contact",
    weight: 0.95,
    cueGood: "Highest contact — steepest angle possible",
    cueWarning: "Contact dropping — losing angle and power",
    cueCritical: "Arm too low — flat smash, easy to return",
  },
  {
    id: "smash-trunk-rotation",
    name: "Trunk rotation into the shot",
    description: "Hip and torso rotation sequence through contact transferring rotational momentum into the smash",
    angle: { joint: "torso", p1: "leftShoulder", p2: "midHip", p3: "rightShoulder" },
    goodRange: [60, 90],
    warningRange: [40, 60],
    criticalRange: [0, 40],
    side: "right",
    phase: "Contact",
    weight: 0.8,
    cueGood: "Rotating through — full body into smash",
    cueWarning: "Partial rotation — arm dominant",
    cueCritical: "Square to net — no torso contribution",
  },
  {
    id: "smash-landing-knee",
    name: "Landing knee flexion for absorption",
    description: "Knee flexion angle on landing after the smash jump to safely decelerate and prepare for recovery",
    angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
    goodRange: [30, 45],
    warningRange: [20, 30],
    criticalRange: [0, 20],
    side: "right",
    phase: "Follow-through",
    weight: 0.7,
    cueGood: "Soft landing — knees absorbing impact",
    cueWarning: "Stiff landing — joint stress building",
    cueCritical: "Legs locked — high injury risk on landing",
  },
];

const badmintonSmashPhases: MovementPhase[] = [
  { name: "Setup", description: "Feet shoulder-width apart, body sideways to net, racket back, non-racket arm pointing at shuttle" },
  { name: "Jump/Scissor kick", description: "Explosive jump with scissor leg motion, both arms extending, body arching backward" },
  { name: "Racket drop", description: "Shoulder reaches maximum external rotation, racket drops behind head, elbow leads" },
  { name: "Acceleration", description: "Hip rotation initiates, trunk snaps forward, arm whips through, wrist cocked" },
  { name: "Contact", description: "Highest possible contact point, arm fully extended, wrist snaps down, full body rotation" },
  { name: "Follow-through", description: "Racket continues down across body, landing on non-dominant foot, knee bends for absorption" },
];

const badmintonClearCheckpoints: BiomechanicalCheckpoint[] = [
  {
    id: "clear-shoulder-er",
    name: "Shoulder external rotation at preparation",
    description: "External shoulder rotation during the preparation phase, less extreme than smash for a higher, deeper trajectory",
    angle: { joint: "rightShoulder", p1: "rightElbow", p2: "rightShoulder", p3: "rightHip" },
    goodRange: [90, 120],
    warningRange: [75, 90],
    criticalRange: [0, 75],
    side: "right",
    phase: "Racket drop",
    weight: 0.8,
    cueGood: "Controlled coil — ready for deep clear",
    cueWarning: "Under-rotated — losing clearance distance",
    cueCritical: "No drop — arming the clear",
  },
  {
    id: "clear-wrist-snap",
    name: "Wrist action at contact (less snap than smash)",
    description: "Moderate wrist flexion at contact — less aggressive than smash to produce a high, deep trajectory rather than steep angle",
    angle: { joint: "rightWrist", p1: "rightElbow", p2: "rightWrist", p3: "rightHand" },
    goodRange: [10, 25],
    warningRange: [0, 10],
    criticalRange: [25, 60],
    side: "right",
    phase: "Contact",
    weight: 0.7,
    cueGood: "Controlled release — height over power",
    cueWarning: "No snap — clear falls short",
    cueCritical: "Too much snap — flattening trajectory",
  },
  {
    id: "clear-contact-forward",
    name: "Contact point slightly more forward than smash",
    description: "Contact point positioned slightly ahead of the body for a higher launch angle on the clear",
    angle: { joint: "rightShoulder", p1: "rightElbow", p2: "rightShoulder", p3: "nose" },
    goodRange: [15, 25],
    warningRange: [5, 15],
    criticalRange: [0, 5],
    side: "right",
    phase: "Contact",
    weight: 0.75,
    cueGood: "Contact out front — good launch angle",
    cueWarning: "Contact too far back — losing height",
    cueCritical: "Contact overhead — defensive lob only",
  },
  {
    id: "clear-arm-extension",
    name: "Arm extension at contact",
    description: "Full arm extension at contact ensuring maximum reach and clean transfer of force",
    angle: { joint: "rightElbow", p1: "rightShoulder", p2: "rightElbow", p3: "rightWrist" },
    goodRange: [165, 180],
    warningRange: [150, 165],
    criticalRange: [0, 150],
    side: "right",
    phase: "Contact",
    weight: 0.85,
    cueGood: "Arm locked — full extension reached",
    cueWarning: "Arm bent — losing leverage",
    cueCritical: "Elbow collapsed — no power",
  },
];

const badmintonClearPhases: MovementPhase[] = [
  { name: "Preparation", description: "Body positioned under the shuttle, racket arm loaded, non-racket arm raised for balance" },
  { name: "Racket drop", description: "Racket drops behind head, shoulder externally rotated, elbow at 90°" },
  { name: "Swing", description: "Arm accelerates upward and forward with moderate wrist cock, body rotates into shot" },
  { name: "Contact", description: "Contact slightly ahead of body, arm extended, controlled wrist release for height and depth" },
  { name: "Follow-through", description: "Racket follows through high and forward, weight shifts onto front foot" },
];

const badmintonLungeCheckpoints: BiomechanicalCheckpoint[] = [
  {
    id: "lunge-lead-knee",
    name: "Lead knee angle at lunge",
    description: "Front knee angle at maximum lunge depth — critical to keep knee behind toes to prevent ACL and patellar injury",
    angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
    goodRange: [100, 130],
    warningRange: [90, 100],
    criticalRange: [0, 90],
    side: "right",
    phase: "Lunge",
    weight: 1.0,
    cueGood: "Knee behind toe — safe, efficient lunge",
    cueWarning: "Knee creeping forward — increased ACL risk",
    cueCritical: "Knee past toe — dangerous joint loading",
  },
  {
    id: "lunge-trail-leg",
    name: "Trail leg angle at lunge",
    description: "Extension angle of the trail leg providing stability and stretch-shortening for recovery push-off",
    angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
    goodRange: [150, 180],
    warningRange: [120, 150],
    criticalRange: [0, 120],
    side: "left",
    phase: "Lunge",
    weight: 0.6,
    cueGood: "Trail leg extended — stable base",
    cueWarning: "Trail leg too bent — losing recovery power",
    cueCritical: "Trail leg collapsed — can't push back",
  },
  {
    id: "lunge-trunk-lean",
    name: "Trunk lean forward — spine angle vs vertical",
    description: "Forward inclination of the torso relative to vertical during the lunge, affecting balance and recovery",
    angle: { joint: "spine", p1: "rightHip", p2: "nose", p3: "leftHip" },
    goodRange: [30, 45],
    warningRange: [20, 30],
    criticalRange: [0, 20],
    side: "both",
    phase: "Lunge",
    weight: 0.75,
    cueGood: "Forward lean — momentum into the shot",
    cueWarning: "Too upright — reaching with arm only",
    cueCritical: "Leaning back — off balance, weak shot",
  },
  {
    id: "lunge-ankle-dorsiflexion",
    name: "Ankle dorsiflexion at lunge",
    description: "Dorsiflexion angle of the lead ankle allowing the knee to track forward safely over the foot",
    angle: { joint: "rightAnkle", p1: "rightKnee", p2: "rightAnkle", p3: "rightFootIndex" },
    goodRange: [20, 35],
    warningRange: [35, 45],
    criticalRange: [0, 20],
    side: "right",
    phase: "Lunge",
    weight: 0.7,
    cueGood: "Ankle flexed — stable landing platform",
    cueWarning: "Excessive dorsiflexion — ankle at end range",
    cueCritical: "Ankle stiff — landing flat, no absorption",
  },
  {
    id: "lunge-recovery-knee-drive",
    name: "Recovery knee drive angle",
    description: "Hip flexion angle of the recovery leg as it drives forward to return to base position after the lunge",
    angle: { joint: "leftHip", p1: "leftKnee", p2: "leftHip", p3: "rightHip" },
    goodRange: [60, 90],
    warningRange: [40, 60],
    criticalRange: [0, 40],
    side: "left",
    phase: "Recovery",
    weight: 0.65,
    cueGood: "Knee driving up — explosive recovery",
    cueWarning: "Low knee drive — slow recovery",
    cueCritical: "No drive — stuck in lunge position",
  },
];

const badmintonLungePhases: MovementPhase[] = [
  { name: "Split step", description: "Small hop loading both legs, ready to react to opponent's shot direction" },
  { name: "Drive phase", description: "Explosive step toward the shuttle, lead leg extends forward, trail leg drives" },
  { name: "Lunge", description: "Lead foot lands with heel contact, knee bends to absorb, racket extends to shuttle" },
  { name: "Recovery", description: "Trail leg drives forward, weight pushes off lead leg, return to ready position" },
];

export const badmintonSmash: ExerciseBiomechanics = {
  id: "badminton-smash",
  name: "Badminton Smash",
  aliases: ["smash", "jump smash", "overhead smash"],
  category: "badminton",
  description:
    "The badminton smash is the fastest racket stroke in sports, reaching shuttle speeds over 400 km/h. It combines a powerful jump (scissor kick), extreme shoulder external rotation (120-150°), rapid elbow extension, and a pronated wrist snap to drive the shuttle steeply downward into the opponent's court.",
  tags: ["smash", "overhead", "power", "jump", "scissor-kick", "dominant-arm", "attack"],
  landmarks: [
    "nose", "leftEye", "rightEye", "leftEar", "rightEar",
    "leftShoulder", "rightShoulder", "leftElbow", "rightElbow",
    "leftWrist", "rightWrist", "leftHip", "rightHip",
    "leftKnee", "rightKnee", "leftAnkle", "rightAnkle",
    "leftHeel", "rightHeel", "leftFootIndex", "rightFootIndex",
  ],
  checkpoints: badmintonSmashCheckpoints,
  phases: badmintonSmashPhases,
};

export const badmintonClear: ExerciseBiomechanics = {
  id: "badminton-clear",
  name: "Badminton Clear / Overhead",
  aliases: ["clear", "overhead clear", "defensive clear", "attacking clear"],
  category: "badminton",
  description:
    "The badminton clear is an overhead stroke that sends the shuttle high and deep to the opponent's baseline. It uses a similar throwing motion to the smash but with less wrist snap and a slightly more forward contact point to achieve a higher launch angle for depth rather than steepness.",
  tags: ["clear", "overhead", "defensive", "attacking", "placement", "dominant-arm"],
  landmarks: [
    "nose", "leftEye", "rightEye", "leftEar", "rightEar",
    "leftShoulder", "rightShoulder", "leftElbow", "rightElbow",
    "leftWrist", "rightWrist", "leftHip", "rightHip",
    "leftKnee", "rightKnee", "leftAnkle", "rightAnkle",
    "leftHeel", "rightHeel", "leftFootIndex", "rightFootIndex",
  ],
  checkpoints: badmintonClearCheckpoints,
  phases: badmintonClearPhases,
};

export const badmintonLunge: ExerciseBiomechanics = {
  id: "badminton-lunge",
  name: "Badminton Lunge",
  aliases: ["lunge", "court coverage lunge", "forward lunge", "recovery lunge"],
  category: "badminton",
  description:
    "The badminton lunge is the primary footwork pattern for court coverage, involving an explosive step, deep knee bend, and rapid recovery. Proper lunge mechanics are critical for injury prevention (especially ACL and patellar tendinopathy) and maintaining court positioning.",
  tags: ["footwork", "lunge", "defensive", "recovery", "injury-prevention", "lower-body"],
  landmarks: [
    "nose", "leftEye", "rightEye", "leftEar", "rightEar",
    "leftShoulder", "rightShoulder", "leftElbow", "rightElbow",
    "leftWrist", "rightWrist", "leftHip", "rightHip",
    "leftKnee", "rightKnee", "leftAnkle", "rightAnkle",
    "leftHeel", "rightHeel", "leftFootIndex", "rightFootIndex",
  ],
  checkpoints: badmintonLungeCheckpoints,
  phases: badmintonLungePhases,
};

const badmintonExercises: ExerciseBiomechanics[] = [
  badmintonSmash,
  badmintonClear,
  badmintonLunge,
];

export default badmintonExercises;
