import type {
  ExerciseBiomechanics,
  BiomechanicalCheckpoint,
  MovementPhase,
} from "../../types";

const tennisServeCheckpoints: BiomechanicalCheckpoint[] = [
  {
    id: "serve-torso-tilt",
    name: "Torso tilt at trophy",
    description: "Lateral trunk lean away from net at trophy phase to create shoulder slope for upward swing",
    angle: { joint: "torso", p1: "leftShoulder", p2: "rightHip", p3: "rightShoulder" },
    goodRange: [8, 15],
    warningRange: [5, 8],
    criticalRange: [0, 5],
    side: "right",
    phase: "Trophy pose",
    weight: 0.75,
    cueGood: "Lean tower — tilt away from net",
    cueWarning: "Too upright — losing shoulder slope",
    cueCritical: "Standing straight — no coil loaded",
  },
  {
    id: "serve-shoulder-er",
    name: "Shoulder external rotation at racket drop",
    description: "Maximum external rotation of dominant shoulder at the base of the backscratch position",
    angle: { joint: "rightShoulder", p1: "rightElbow", p2: "rightShoulder", p3: "rightHip" },
    goodRange: [90, 120],
    warningRange: [75, 90],
    criticalRange: [0, 75],
    side: "right",
    phase: "Racket drop (scratch)",
    weight: 0.9,
    cueGood: "Loaded slingshot — shoulder coiled deep",
    cueWarning: "Not enough external rotation — losing power",
    cueCritical: "Arm too high — no racket drop lag",
  },
  {
    id: "serve-elbow-flex",
    name: "Elbow flexion at racket drop",
    description: "Elbow bend angle at the bottom of the racket drop, storing elastic energy for acceleration",
    angle: { joint: "rightElbow", p1: "rightShoulder", p2: "rightElbow", p3: "rightWrist" },
    goodRange: [80, 100],
    warningRange: [70, 80],
    criticalRange: [0, 70],
    side: "right",
    phase: "Racket drop (scratch)",
    weight: 0.8,
    cueGood: "90° spring — elbow loaded like a bow",
    cueWarning: "Too straight — losing whip effect",
    cueCritical: "Arm nearly locked — no snap potential",
  },
  {
    id: "serve-x-factor",
    name: "Hip-shoulder separation at trophy (X-factor)",
    description: "Rotational separation between hips and shoulders storing elastic torsional energy",
    angle: { joint: "torso", p1: "leftHip", p2: "midHip", p3: "leftShoulder" },
    goodRange: [30, 40],
    warningRange: [20, 30],
    criticalRange: [0, 20],
    side: "both",
    phase: "Trophy pose",
    weight: 0.85,
    cueGood: "X-factor coiled — hips lead shoulders",
    cueWarning: "Too open — losing stretch-shorten cycle",
    cueCritical: "Square to net — no rotational preload",
  },
  {
    id: "serve-knee-bend",
    name: "Knee bend angle at trophy",
    description: "Front knee flexion storing leg drive energy for upward propulsion into contact",
    angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
    goodRange: [90, 120],
    warningRange: [75, 90],
    criticalRange: [0, 75],
    side: "right",
    phase: "Trophy pose",
    weight: 0.7,
    cueGood: "Loaded legs — spring coil ready",
    cueWarning: "Too straight — losing ground force",
    cueCritical: "Standing tall — no leg drive",
  },
  {
    id: "serve-contact-height",
    name: "Contact height — arm and racket extension",
    description: "Full vertical extension of shoulder-wrist line at ball contact for maximum reach",
    angle: { joint: "rightArm", p1: "rightShoulder", p2: "rightWrist", p3: "rightHip" },
    goodRange: [170, 185],
    warningRange: [155, 170],
    criticalRange: [0, 155],
    side: "right",
    phase: "Contact",
    weight: 0.95,
    cueGood: "Sky-high contact — full extension reached",
    cueWarning: "Contact dropping — losing height advantage",
    cueCritical: "Arm bent at contact — power leak",
  },
  {
    id: "serve-trunk-rotation",
    name: "Trunk rotation into court at contact",
    description: "Hip rotation toward the net at contact transferring rotational energy into the serve",
    angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "leftHip" },
    goodRange: [45, 70],
    warningRange: [30, 45],
    criticalRange: [0, 30],
    side: "right",
    phase: "Contact",
    weight: 0.7,
    cueGood: "Hips opened — rotating into shot",
    cueWarning: "Too closed — power from arm only",
    cueCritical: "Facing sideways — no torso torque",
  },
  {
    id: "serve-non-dominant-arm",
    name: "Non-dominant arm tuck position",
    description: "Non-dominant arm tucks into torso after toss to allow shoulder-over-shoulder pronation motion",
    angle: { joint: "leftArm", p1: "leftShoulder", p2: "leftElbow", p3: "leftWrist" },
    goodRange: [20, 50],
    warningRange: [50, 80],
    criticalRange: [80, 180],
    side: "left",
    phase: "Acceleration",
    weight: 0.6,
    cueGood: "Tucked tight — clean pronation path",
    cueWarning: "Arm drifting — blocking shoulder rotation",
    cueCritical: "Arm flailing — losing rotational speed",
  },
  {
    id: "serve-wrist-snap",
    name: "Wrist flexion through contact",
    description: "Wrist snap at contact applying final pronation and flexion for topspin and pace",
    angle: { joint: "rightWrist", p1: "rightElbow", p2: "rightWrist", p3: "rightHand" },
    goodRange: [10, 30],
    warningRange: [30, 45],
    criticalRange: [0, 10],
    side: "right",
    phase: "Contact",
    weight: 0.8,
    cueGood: "Snap crisp — wrist fired through ball",
    cueWarning: "Wrist too firm — losing racquet head speed",
    cueCritical: "No snap — all arm, no whip",
  },
];

const tennisServePhases: MovementPhase[] = [
  { name: "Stance", description: "Feet shoulder-width apart, front toe aligned with back heel, weight on back foot" },
  { name: "Trophy pose", description: "Both arms up, racket pointing skyward, knees bent, torso coiled away from net" },
  { name: "Racket drop (scratch)", description: "Racket drops behind back, shoulder externally rotated, elbow at 90°, legs loading" },
  { name: "Acceleration", description: "Leg drive initiates, hips rotate, trunk uncoils, racket whips upward" },
  { name: "Contact", description: "Full extension at highest reach point, wrist snap, full body rotation into court" },
  { name: "Follow-through", description: "Racket continues across body, weight lands forward, non-dominant arm tucks" },
];

const tennisForehandCheckpoints: BiomechanicalCheckpoint[] = [
  {
    id: "fh-unit-turn",
    name: "Unit turn shoulder-hip separation",
    description: "Rotational separation between shoulders and hips during the coil phase storing elastic energy",
    angle: { joint: "torso", p1: "rightShoulder", p2: "midHip", p3: "rightHip" },
    goodRange: [40, 60],
    warningRange: [30, 40],
    criticalRange: [0, 30],
    side: "right",
    phase: "Unit turn",
    weight: 0.8,
    cueGood: "Coil loaded — shoulders turned past hips",
    cueWarning: "Partial coil — losing stretch reflex",
    cueCritical: "Arm-only swing — no body rotation",
  },
  {
    id: "fh-elbow-contact",
    name: "Arm extension at contact",
    description: "Elbow angle at the moment of contact — slightly bent for stability and power transfer",
    angle: { joint: "rightElbow", p1: "rightShoulder", p2: "rightElbow", p3: "rightWrist" },
    goodRange: [150, 170],
    warningRange: [140, 150],
    criticalRange: [0, 140],
    side: "right",
    phase: "Contact",
    weight: 0.85,
    cueGood: "Firm extension — power through the ball",
    cueWarning: "Too bent — arm collapse at contact",
    cueCritical: "Chicken wing — no reach or stability",
  },
  {
    id: "fh-wrist-contact",
    name: "Wrist angle at contact",
    description: "Wrist laid back slightly at contact for topspin generation and racquet head stability",
    angle: { joint: "rightWrist", p1: "rightElbow", p2: "rightWrist", p3: "rightHand" },
    goodRange: [155, 175],
    warningRange: [140, 155],
    criticalRange: [0, 140],
    side: "right",
    phase: "Contact",
    weight: 0.75,
    cueGood: "Laid back — stable racquet face through zone",
    cueWarning: "Wrist breaking down — losing control",
    cueCritical: "Flapping wrist — inconsistent contact",
  },
  {
    id: "fh-front-knee-flex",
    name: "Front knee flexion at contact",
    description: "Knee bend of the front leg providing stability and ground force transfer at contact",
    angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
    goodRange: [30, 45],
    warningRange: [20, 30],
    criticalRange: [0, 20],
    side: "left",
    phase: "Contact",
    weight: 0.65,
    cueGood: "Athletic base — knee loaded and stable",
    cueWarning: "Too straight — floating through contact",
    cueCritical: "Leg locked — no ground connection",
  },
  {
    id: "fh-trunk-rotation",
    name: "Trunk rotation through contact",
    description: "Hip turn into the shot transferring rotational kinetic energy from the coil into the ball",
    angle: { joint: "rightHip", p1: "leftShoulder", p2: "rightHip", p3: "rightShoulder" },
    goodRange: [60, 90],
    warningRange: [40, 60],
    criticalRange: [0, 40],
    side: "right",
    phase: "Contact",
    weight: 0.8,
    cueGood: "Hips fire through — full kinetic chain",
    cueWarning: "Hips late — arm doing the work",
    cueCritical: "Facing sideways — no rotation into shot",
  },
  {
    id: "fh-weight-transfer",
    name: "Weight transfer through front knee change",
    description: "Change in front knee angle from setup to contact indicating forward weight shift",
    angle: { joint: "leftKnee", p1: "leftAnkle", p2: "leftKnee", p3: "leftHip" },
    goodRange: [10, 25],
    warningRange: [5, 10],
    criticalRange: [0, 5],
    side: "left",
    phase: "Acceleration",
    weight: 0.6,
    cueGood: "Weight forward — driving into the ball",
    cueWarning: "Staying back — losing power from ground",
    cueCritical: "No shift — weight on back foot",
  },
  {
    id: "fh-follow-through",
    name: "Follow-through arm position over shoulder",
    description: "Racket finishes over the non-dominant shoulder indicating proper forearm pronation through contact",
    angle: { joint: "rightShoulder", p1: "rightElbow", p2: "rightShoulder", p3: "leftShoulder" },
    goodRange: [30, 60],
    warningRange: [60, 90],
    criticalRange: [90, 180],
    side: "right",
    phase: "Follow-through",
    weight: 0.5,
    cueGood: "Over the shoulder — full pronation path",
    cueWarning: "Around the neck — incomplete rotation",
    cueCritical: "Wrapping low — restricted follow-through",
  },
];

const tennisForehandPhases: MovementPhase[] = [
  { name: "Split step", description: "Small hop loading both legs as opponent contacts ball, ready to move" },
  { name: "Unit turn", description: "Shoulders rotate as a unit with hips, racket arm begins to set, non-dominant hand supports throat" },
  { name: "Racket back", description: "Racket taken back behind body, wrist laid back, core coiled, weight on back foot" },
  { name: "Acceleration", description: "Weight transfers forward, hips rotate, arm accelerates from low to high, wrist releases" },
  { name: "Contact", description: "Racket meets ball in front of body, arm extended, wrist firm, body open to net" },
  { name: "Follow-through", description: "Racket finishes over non-dominant shoulder, weight fully forward, balanced" },
];

const tennisBackhandCheckpoints: BiomechanicalCheckpoint[] = [
  {
    id: "bh-shoulder-turn",
    name: "Shoulder turn angle from baseline",
    description: "Shoulder rotation away from the net during the unit turn for a one-handed backhand",
    angle: { joint: "torso", p1: "leftShoulder", p2: "midHip", p3: "rightShoulder" },
    goodRange: [80, 100],
    warningRange: [65, 80],
    criticalRange: [0, 65],
    side: "right",
    phase: "Unit turn",
    weight: 0.85,
    cueGood: "Shoulders turned 90° — full coil achieved",
    cueWarning: "Partial turn — losing rotational power",
    cueCritical: "Open stance — arm swing only",
  },
  {
    id: "bh-arm-extension",
    name: "Both arm extension at contact",
    description: "Both arms fully extended through contact with the non-dominant arm reaching back for counterbalance",
    angle: { joint: "rightElbow", p1: "rightShoulder", p2: "rightElbow", p3: "rightWrist" },
    goodRange: [165, 180],
    warningRange: [150, 165],
    criticalRange: [0, 150],
    side: "right",
    phase: "Contact",
    weight: 0.9,
    cueGood: "Arm locked — long lever through the ball",
    cueWarning: "Arm bending — losing power and reach",
    cueCritical: "Collapsed arm — no stability at contact",
  },
  {
    id: "bh-front-leg-knee",
    name: "Front leg position and knee flexion at contact",
    description: "Front knee bend providing stable base and forward weight drive through the backhand",
    angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
    goodRange: [25, 40],
    warningRange: [15, 25],
    criticalRange: [0, 15],
    side: "right",
    phase: "Contact",
    weight: 0.65,
    cueGood: "Stable base — knee tracking over foot",
    cueWarning: "Too straight — losing ground force",
    cueCritical: "Leg locked — no drive through shot",
  },
  {
    id: "bh-trunk-sequencing",
    name: "Trunk rotation sequencing through contact",
    description: "Sequential rotation of hips then shoulders through the ball for maximum power transfer",
    angle: { joint: "torso", p1: "leftHip", p2: "midHip", p3: "leftShoulder" },
    goodRange: [50, 75],
    warningRange: [35, 50],
    criticalRange: [0, 35],
    side: "right",
    phase: "Acceleration",
    weight: 0.8,
    cueGood: "Hips lead shoulders — kinetic chain firing",
    cueWarning: "Rotating together — losing whip effect",
    cueCritical: "No rotation — arming the ball",
  },
  {
    id: "bh-contact-point",
    name: "Contact point relative to front hip",
    description: "Distance of contact point ahead of the front hip for optimal leverage in a one-handed backhand",
    angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "rightKnee" },
    goodRange: [20, 35],
    warningRange: [10, 20],
    criticalRange: [0, 10],
    side: "right",
    phase: "Contact",
    weight: 0.75,
    cueGood: "Contact out front — maximum leverage",
    cueWarning: "Contact too late — jammed by body",
    cueCritical: "Contact behind hip — zero power potential",
  },
];

const tennisBackhandPhases: MovementPhase[] = [
  { name: "Unit turn", description: "Shoulders rotate almost perpendicular to net, racket taken back with both hands on throat" },
  { name: "Racket back", description: "Non-dominant hand releases, racket drops low and back, wrist cocked, weight loading back leg" },
  { name: "Acceleration", description: "Hips rotate forward, arm swings from low to high through the contact zone" },
  { name: "Contact", description: "Arm fully extended, contact point well ahead of front hip, stable wrist, strings square" },
  { name: "Follow-through", description: "Racket finishes high and around, weight fully on front foot, body open" },
];

export const tennisServe: ExerciseBiomechanics = {
  id: "tennis-serve",
  name: "Tennis Serve",
  aliases: ["serve", "tennis service"],
  category: "tennis",
  description:
    "The tennis serve is the most biomechanically complex stroke in the sport, involving a kinetic chain from the ground up through legs, hips, torso, shoulder, arm, and wrist. The serve uses a throw-and-strike pattern with maximal reach, shoulder external rotation, and wrist pronation to generate power and spin.",
  tags: ["serve", "overhead", "power", "kinetic-chain", "rotation", "dominant-arm"],
  landmarks: [
    "nose", "leftEye", "rightEye", "leftEar", "rightEar",
    "leftShoulder", "rightShoulder", "leftElbow", "rightElbow",
    "leftWrist", "rightWrist", "leftHip", "rightHip",
    "leftKnee", "rightKnee", "leftAnkle", "rightAnkle",
    "leftHeel", "rightHeel", "leftFootIndex", "rightFootIndex",
  ],
  checkpoints: tennisServeCheckpoints,
  phases: tennisServePhases,
};

export const tennisForehand: ExerciseBiomechanics = {
  id: "tennis-forehand",
  name: "Tennis Forehand",
  aliases: ["forehand", "fh", "forehand drive"],
  category: "tennis",
  description:
    "The tennis forehand is an open-chain rotational stroke generating power through sequential hip-shoulder rotation, weight transfer, and arm extension. Modern forehands use heavy topspin generated by a low-to-high swing path and wrist lag-release mechanics.",
  tags: ["groundstroke", "forehand", "rotation", "open-stance", "topspin", "dominant-arm"],
  landmarks: [
    "nose", "leftEye", "rightEye", "leftEar", "rightEar",
    "leftShoulder", "rightShoulder", "leftElbow", "rightElbow",
    "leftWrist", "rightWrist", "leftHip", "rightHip",
    "leftKnee", "rightKnee", "leftAnkle", "rightAnkle",
    "leftHeel", "rightHeel", "leftFootIndex", "rightFootIndex",
  ],
  checkpoints: tennisForehandCheckpoints,
  phases: tennisForehandPhases,
};

export const tennisBackhand: ExerciseBiomechanics = {
  id: "tennis-backhand-one-handed",
  name: "Tennis Backhand (One-Handed)",
  aliases: ["backhand", "bh", "one-handed backhand", "1hbh"],
  category: "tennis",
  description:
    "The one-handed backhand relies on full shoulder rotation (≈90°), a stable front arm lever, and precise hip-shoulder sequencing. Unlike the two-handed variant, it demands greater shoulder strength, timing, and contact-point discipline.",
  tags: ["groundstroke", "backhand", "one-handed", "rotation", "precision", "dominant-arm"],
  landmarks: [
    "nose", "leftEye", "rightEye", "leftEar", "rightEar",
    "leftShoulder", "rightShoulder", "leftElbow", "rightElbow",
    "leftWrist", "rightWrist", "leftHip", "rightHip",
    "leftKnee", "rightKnee", "leftAnkle", "rightAnkle",
    "leftHeel", "rightHeel", "leftFootIndex", "rightFootIndex",
  ],
  checkpoints: tennisBackhandCheckpoints,
  phases: tennisBackhandPhases,
};

const tennisExercises: ExerciseBiomechanics[] = [
  tennisServe,
  tennisForehand,
  tennisBackhand,
];

export default tennisExercises;
