export const SPORTS = [
  "Running",
  "Cycling",
  "Swimming",
  "Weightlifting",
  "CrossFit",
  "Golf",
  "Tennis",
  "Basketball",
  "Soccer",
  "Football",
  "Baseball",
  "Volleyball",
  "Boxing",
  "MMA",
  "Jiu-Jitsu",
  "Yoga",
  "Pilates",
  "Dance",
  "Gymnastics",
  "Rock Climbing",
  "Rowing",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Triathlon",
  "Martial Arts",
  "Functional Training",
  "General Fitness",
  "Pickleball",
  "Badminton",
  "Rugby",
  "Cricket",
  "Lacrosse",
  "Fencing",
  "Archery",
  "Powerlifting",
  "Strongman",
  "Calisthenics",
  "Parkour",
  "Skating",
  "Kayaking",
  "Rafting",
  "Hiking",
  "Mountaineering",
  "Sprinting",
  "Ultra-running",
  "Biathlon",
  "Walking",
  "Kickboxing",
  "Capoeira",
] as const;

export const MUSCLES = [
  "Full Body",
  "Core / Abs",
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Forearms",
  "Glutes",
  "Quads",
  "Hamstrings",
  "Calves",
  "Hip Flexors",
  "Adductors",
  "Abductors",
  "Rotator Cuff",
  "Neck / Traps",
  "Lower Back",
  "Obliques",
  "Upper Chest",
  "Lower Traps",
  "Rhomboids",
  "Teres Major",
  "Teres Minor",
  "Infraspinatus",
  "Supraspinatus",
  "Serratus Anterior",
  "Psoas",
  "TFL",
  "Soleus",
  "Tibialis Anterior",
  "Peroneals",
  "Wrist Flexors",
  "Wrist Extensors",
  "Scalenes",
] as const;

export const EXERCISES = [
  "Squat",
  "Deadlift",
  "Bench Press",
  "Overhead Press",
  "Pull-Up",
  "Row",
  "Clean & Jerk",
  "Snatch",
  "Lunge",
  "Hip Thrust",
  "Leg Press",
  "Lat Pulldown",
  "Cable Row",
  "Dumbbell Curl",
  "Tricep Extension",
  "Plank",
  "Pallof Press",
  "Farmers Walk",
  "Box Jump",
  "Burpee",
  "Kettlebell Swing",
  "Turkish Get-Up",
  "Push-Up",
  "Dip",
  "Face Pull",
  "Lateral Raise",
  "Hammer Curl",
  "Romanian Deadlift",
  "Good Morning",
  "Bulgarian Split Squat",
  "Step-Up",
  "Sprint",
  "Agility Drill",
  "Medicine Ball Throw",
  "Band Pull-Apart",
  "Glute Bridge",
  "Clamshell",
  "Side Plank",
  "Dead Bug",
  "Bird Dog",
  "Wall Sit",
  "Calf Raise",
  "Wrist Curl",
  "Neck Flexion",
  "Zercher Squat",
  "Front Squat",
  "Pause Squat",
  "Deficit Deadlift",
  "Sumo Deadlift",
  "Trap Bar Deadlift",
  "Incline Bench",
  "Decline Bench",
  "Dumbbell Bench",
  "Close-Grip Bench",
  "Wide-Grip Pull-Up",
  "Chin-Up",
  "Australian Row",
  "T-Bar Row",
  "Single-Arm Row",
  "Inverted Row",
  "Landmine Press",
  "Arnold Press",
  "Cuban Press",
  "Push Press",
  "Behind-the-Neck Press",
  "Skull Crusher",
  "Overhead Tricep Extension",
  "Preacher Curl",
  "Spider Curl",
  "Reverse Curl",
  "Leg Extension",
  "Leg Curl",
  "Hip Adduction",
  "Hip Abduction",
  "Donkey Calf Raise",
  "Seated Calf Raise",
  "Hanging Leg Raise",
  "Ab Wheel",
  "Dragon Flag",
  "Copenhagen Plank",
  "Reverse Hyper",
  "Back Extension",
  "Sled Push",
  "Sled Pull",
  "Prowler Sprint",
  "Battle Ropes",
] as const;

export type Sport = (typeof SPORTS)[number];
export type Muscle = (typeof MUSCLES)[number];
export type Exercise = (typeof EXERCISES)[number];
