export interface NutrientDef {
  key: string;
  label: string;
  unit: string;
  target: number;
  category: 'macro' | 'micro';
  subcategory?: 'protein' | 'carbs' | 'fats' | 'vitamin' | 'mineral';
  parent?: string;
}

export const NUTRIENT_DEFS: NutrientDef[] = [
  { key: 'calories', label: 'Calories', unit: 'kcal', target: 2400, category: 'macro', subcategory: 'protein' },
  { key: 'protein_g', label: 'Protein', unit: 'g', target: 168, category: 'macro', subcategory: 'protein' },
  { key: 'carbs_g', label: 'Carbs', unit: 'g', target: 290, category: 'macro', subcategory: 'carbs' },
  { key: 'sugars_g', label: 'Sugars', unit: 'g', target: 36, category: 'macro', subcategory: 'carbs', parent: 'carbs_g' },
  { key: 'fiber_g', label: 'Fiber', unit: 'g', target: 38, category: 'macro', subcategory: 'carbs', parent: 'carbs_g' },
  { key: 'fats_g', label: 'Fats', unit: 'g', target: 75, category: 'macro', subcategory: 'fats' },
  { key: 'saturated_fat_g', label: 'Saturated', unit: 'g', target: 20, category: 'macro', subcategory: 'fats', parent: 'fats_g' },
  { key: 'unsaturated_fat_g', label: 'Unsaturated', unit: 'g', target: 55, category: 'macro', subcategory: 'fats', parent: 'fats_g' },
  { key: 'vitamin_a_mcg', label: 'Vitamin A', unit: 'mcg', target: 900, category: 'micro', subcategory: 'vitamin' },
  { key: 'vitamin_c_mg', label: 'Vitamin C', unit: 'mg', target: 90, category: 'micro', subcategory: 'vitamin' },
  { key: 'vitamin_d_iu', label: 'Vitamin D', unit: 'IU', target: 600, category: 'micro', subcategory: 'vitamin' },
  { key: 'vitamin_e_mg', label: 'Vitamin E', unit: 'mg', target: 15, category: 'micro', subcategory: 'vitamin' },
  { key: 'vitamin_k_mcg', label: 'Vitamin K', unit: 'mcg', target: 120, category: 'micro', subcategory: 'vitamin' },
  { key: 'b12_mcg', label: 'B12', unit: 'mcg', target: 2.4, category: 'micro', subcategory: 'vitamin' },
  { key: 'folate_mcg', label: 'Folate', unit: 'mcg', target: 400, category: 'micro', subcategory: 'vitamin' },
  { key: 'iron_mg', label: 'Iron', unit: 'mg', target: 18, category: 'micro', subcategory: 'mineral' },
  { key: 'calcium_mg', label: 'Calcium', unit: 'mg', target: 1000, category: 'micro', subcategory: 'mineral' },
  { key: 'magnesium_mg', label: 'Magnesium', unit: 'mg', target: 420, category: 'micro', subcategory: 'mineral' },
  { key: 'zinc_mg', label: 'Zinc', unit: 'mg', target: 11, category: 'micro', subcategory: 'mineral' },
  { key: 'potassium_mg', label: 'Potassium', unit: 'mg', target: 4700, category: 'micro', subcategory: 'mineral' },
  { key: 'sodium_mg', label: 'Sodium', unit: 'mg', target: 2300, category: 'micro', subcategory: 'mineral' },
];

export type NutrientMap = Record<string, number>;

export function getStatus(current: number, target: number): 'good' | 'warning' | 'over' {
  if (target <= 0) return 'good';
  const ratio = current / target;
  if (ratio > 1.1) return 'over';
  if (ratio >= 0.85) return 'warning';
  return 'good';
}

export const STATUS_COLORS = {
  good: '#22c55e',
  warning: '#f59e0b',
  over: '#ef4444',
};

export const MACRO_CALORIES: Record<string, number> = {
  protein_g: 4,
  carbs_g: 4,
  fats_g: 9,
};

export type Cuisine = 'north-american' | 'indian' | 'east-asian' | 'southeast-asian';
export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';

export interface FoodItem {
  id: string;
  name: string;
  serving: string;
  cuisine: Cuisine;
  mealType: MealType;
  nutrients: NutrientMap;
}

const INDIAN_FOODS: FoodItem[] = [
  { id: '1', name: 'Dal (cooked)', serving: '1 cup (200g)', cuisine: 'indian', mealType: 'lunch', nutrients: { calories: 220, protein_g: 16, carbs_g: 38, sugars_g: 2, fiber_g: 8, fats_g: 1, saturated_fat_g: 0.2, unsaturated_fat_g: 0.8, vitamin_a_mcg: 20, vitamin_c_mg: 2, vitamin_d_iu: 0, vitamin_e_mg: 0.3, vitamin_k_mcg: 5, b12_mcg: 0, folate_mcg: 180, iron_mg: 3.5, calcium_mg: 40, magnesium_mg: 50, zinc_mg: 1.5, potassium_mg: 400, sodium_mg: 10 } },
  { id: '2', name: 'Roti (whole wheat)', serving: '1 medium (40g)', cuisine: 'indian', mealType: 'lunch', nutrients: { calories: 120, protein_g: 4, carbs_g: 24, sugars_g: 0.5, fiber_g: 3, fats_g: 0.5, saturated_fat_g: 0.1, unsaturated_fat_g: 0.4, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.1, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 20, iron_mg: 1.2, calcium_mg: 10, magnesium_mg: 20, zinc_mg: 0.5, potassium_mg: 80, sodium_mg: 120 } },
  { id: '4', name: 'White Rice (cooked)', serving: '1 cup (180g)', cuisine: 'indian', mealType: 'lunch', nutrients: { calories: 240, protein_g: 4, carbs_g: 53, sugars_g: 0, fiber_g: 1, fats_g: 0.5, saturated_fat_g: 0.1, unsaturated_fat_g: 0.4, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 80, iron_mg: 2, calcium_mg: 10, magnesium_mg: 15, zinc_mg: 0.5, potassium_mg: 60, sodium_mg: 2 } },
  { id: '9', name: 'Paneer (cottage cheese)', serving: '100g', cuisine: 'indian', mealType: 'dinner', nutrients: { calories: 265, protein_g: 18, carbs_g: 1.2, sugars_g: 1.2, fiber_g: 0, fats_g: 21, saturated_fat_g: 13, unsaturated_fat_g: 8, vitamin_a_mcg: 80, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.1, vitamin_k_mcg: 1, b12_mcg: 0.4, folate_mcg: 12, iron_mg: 0.2, calcium_mg: 208, magnesium_mg: 15, zinc_mg: 0.5, potassium_mg: 100, sodium_mg: 15 } },
  { id: 'i1', name: 'Chicken Curry', serving: '1 cup (250g)', cuisine: 'indian', mealType: 'dinner', nutrients: { calories: 310, protein_g: 28, carbs_g: 8, sugars_g: 2, fiber_g: 1, fats_g: 18, saturated_fat_g: 6, unsaturated_fat_g: 12, vitamin_a_mcg: 60, vitamin_c_mg: 5, vitamin_d_iu: 0, vitamin_e_mg: 0.8, vitamin_k_mcg: 2, b12_mcg: 0.5, folate_mcg: 15, iron_mg: 1.5, calcium_mg: 30, magnesium_mg: 35, zinc_mg: 1.2, potassium_mg: 380, sodium_mg: 680 } },
  { id: 'i2', name: 'Sambar', serving: '1 cup (200g)', cuisine: 'indian', mealType: 'lunch', nutrients: { calories: 180, protein_g: 10, carbs_g: 30, sugars_g: 3, fiber_g: 10, fats_g: 3, saturated_fat_g: 0.5, unsaturated_fat_g: 2.5, vitamin_a_mcg: 150, vitamin_c_mg: 8, vitamin_d_iu: 0, vitamin_e_mg: 0.4, vitamin_k_mcg: 10, b12_mcg: 0, folate_mcg: 60, iron_mg: 2.5, calcium_mg: 60, magnesium_mg: 45, zinc_mg: 1, potassium_mg: 350, sodium_mg: 400 } },
  { id: 'i3', name: 'Dosa (plain)', serving: '1 medium (80g)', cuisine: 'indian', mealType: 'breakfast', nutrients: { calories: 140, protein_g: 4, carbs_g: 28, sugars_g: 0, fiber_g: 1, fats_g: 2, saturated_fat_g: 0.3, unsaturated_fat_g: 1.7, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.1, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 12, iron_mg: 1.5, calcium_mg: 8, magnesium_mg: 12, zinc_mg: 0.3, potassium_mg: 50, sodium_mg: 350 } },
  { id: 'i4', name: 'Idli (steamed)', serving: '2 pieces (80g)', cuisine: 'indian', mealType: 'breakfast', nutrients: { calories: 130, protein_g: 4, carbs_g: 28, sugars_g: 0, fiber_g: 1, fats_g: 0.5, saturated_fat_g: 0.1, unsaturated_fat_g: 0.4, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 10, iron_mg: 1.2, calcium_mg: 6, magnesium_mg: 10, zinc_mg: 0.3, potassium_mg: 40, sodium_mg: 200 } },
  { id: 'i5', name: 'Chana Masala', serving: '1 cup (200g)', cuisine: 'indian', mealType: 'lunch', nutrients: { calories: 250, protein_g: 12, carbs_g: 35, sugars_g: 6, fiber_g: 10, fats_g: 7, saturated_fat_g: 1, unsaturated_fat_g: 6, vitamin_a_mcg: 80, vitamin_c_mg: 10, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 4, b12_mcg: 0, folate_mcg: 140, iron_mg: 3, calcium_mg: 60, magnesium_mg: 55, zinc_mg: 1.2, potassium_mg: 420, sodium_mg: 500 } },
  { id: 'i6', name: 'Palak Paneer', serving: '1 cup (200g)', cuisine: 'indian', mealType: 'dinner', nutrients: { calories: 230, protein_g: 14, carbs_g: 8, sugars_g: 2, fiber_g: 4, fats_g: 17, saturated_fat_g: 10, unsaturated_fat_g: 7, vitamin_a_mcg: 600, vitamin_c_mg: 12, vitamin_d_iu: 0, vitamin_e_mg: 1.2, vitamin_k_mcg: 350, b12_mcg: 0.3, folate_mcg: 80, iron_mg: 2.5, calcium_mg: 180, magnesium_mg: 60, zinc_mg: 0.8, potassium_mg: 300, sodium_mg: 450 } },
  { id: 'i7', name: 'Aloo Gobi', serving: '1 cup (180g)', cuisine: 'indian', mealType: 'lunch', nutrients: { calories: 160, protein_g: 4, carbs_g: 20, sugars_g: 3, fiber_g: 4, fats_g: 8, saturated_fat_g: 1.5, unsaturated_fat_g: 6.5, vitamin_a_mcg: 30, vitamin_c_mg: 30, vitamin_d_iu: 0, vitamin_e_mg: 0.6, vitamin_k_mcg: 15, b12_mcg: 0, folate_mcg: 40, iron_mg: 1, calcium_mg: 30, magnesium_mg: 25, zinc_mg: 0.4, potassium_mg: 350, sodium_mg: 380 } },
  { id: 'i8', name: 'Basmati Rice (cooked)', serving: '1 cup (160g)', cuisine: 'indian', mealType: 'lunch', nutrients: { calories: 210, protein_g: 4, carbs_g: 45, sugars_g: 0, fiber_g: 0.5, fats_g: 0.5, saturated_fat_g: 0.1, unsaturated_fat_g: 0.4, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 70, iron_mg: 1.5, calcium_mg: 8, magnesium_mg: 12, zinc_mg: 0.4, potassium_mg: 50, sodium_mg: 1 } },
  { id: 'i9', name: 'Raita (cucumber)', serving: '1 cup (150g)', cuisine: 'indian', mealType: 'lunch', nutrients: { calories: 80, protein_g: 4, carbs_g: 6, sugars_g: 4, fiber_g: 0.5, fats_g: 4, saturated_fat_g: 2.5, unsaturated_fat_g: 1.5, vitamin_a_mcg: 30, vitamin_c_mg: 2, vitamin_d_iu: 0, vitamin_e_mg: 0.1, vitamin_k_mcg: 4, b12_mcg: 0.4, folate_mcg: 8, iron_mg: 0.2, calcium_mg: 120, magnesium_mg: 12, zinc_mg: 0.4, potassium_mg: 130, sodium_mg: 60 } },
  { id: 'i10', name: 'Poha (flattened rice)', serving: '1 cup (150g)', cuisine: 'indian', mealType: 'breakfast', nutrients: { calories: 180, protein_g: 4, carbs_g: 32, sugars_g: 2, fiber_g: 2, fats_g: 4, saturated_fat_g: 0.8, unsaturated_fat_g: 3.2, vitamin_a_mcg: 20, vitamin_c_mg: 1, vitamin_d_iu: 0, vitamin_e_mg: 0.2, vitamin_k_mcg: 1, b12_mcg: 0, folate_mcg: 15, iron_mg: 2, calcium_mg: 10, magnesium_mg: 20, zinc_mg: 0.5, potassium_mg: 100, sodium_mg: 300 } },
  { id: 'i11', name: 'Upma (semolina)', serving: '1 cup (180g)', cuisine: 'indian', mealType: 'breakfast', nutrients: { calories: 200, protein_g: 5, carbs_g: 35, sugars_g: 1, fiber_g: 2, fats_g: 5, saturated_fat_g: 1, unsaturated_fat_g: 4, vitamin_a_mcg: 10, vitamin_c_mg: 1, vitamin_d_iu: 0, vitamin_e_mg: 0.2, vitamin_k_mcg: 0.5, b12_mcg: 0, folate_mcg: 20, iron_mg: 1.8, calcium_mg: 15, magnesium_mg: 15, zinc_mg: 0.4, potassium_mg: 80, sodium_mg: 350 } },
  { id: 'i12', name: 'Fish Curry (coconut)', serving: '1 cup (250g)', cuisine: 'indian', mealType: 'dinner', nutrients: { calories: 280, protein_g: 24, carbs_g: 6, sugars_g: 2, fiber_g: 1, fats_g: 17, saturated_fat_g: 12, unsaturated_fat_g: 5, vitamin_a_mcg: 40, vitamin_c_mg: 3, vitamin_d_iu: 200, vitamin_e_mg: 0.5, vitamin_k_mcg: 1, b12_mcg: 2.5, folate_mcg: 10, iron_mg: 1.2, calcium_mg: 50, magnesium_mg: 35, zinc_mg: 0.6, potassium_mg: 350, sodium_mg: 550 } },
  { id: 'i13', name: 'Egg Curry', serving: '1 cup (200g)', cuisine: 'indian', mealType: 'dinner', nutrients: { calories: 220, protein_g: 14, carbs_g: 8, sugars_g: 2, fiber_g: 1, fats_g: 15, saturated_fat_g: 5, unsaturated_fat_g: 10, vitamin_a_mcg: 100, vitamin_c_mg: 4, vitamin_d_iu: 40, vitamin_e_mg: 0.6, vitamin_k_mcg: 1, b12_mcg: 0.8, folate_mcg: 25, iron_mg: 1.5, calcium_mg: 40, magnesium_mg: 15, zinc_mg: 0.8, potassium_mg: 200, sodium_mg: 600 } },
];

const NORTH_AMERICAN_FOODS: FoodItem[] = [
  { id: '3', name: 'Chicken Breast (cooked)', serving: '150g', cuisine: 'north-american', mealType: 'dinner', nutrients: { calories: 247, protein_g: 46, carbs_g: 0, sugars_g: 0, fiber_g: 0, fats_g: 5, saturated_fat_g: 1.5, unsaturated_fat_g: 3.5, vitamin_a_mcg: 5, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.2, vitamin_k_mcg: 0, b12_mcg: 0.6, folate_mcg: 5, iron_mg: 1, calcium_mg: 15, magnesium_mg: 30, zinc_mg: 1, potassium_mg: 330, sodium_mg: 75 } },
  { id: '5', name: 'Egg (whole, boiled)', serving: '1 large (50g)', cuisine: 'north-american', mealType: 'breakfast', nutrients: { calories: 78, protein_g: 6, carbs_g: 0.6, sugars_g: 0.6, fiber_g: 0, fats_g: 5, saturated_fat_g: 1.6, unsaturated_fat_g: 3.4, vitamin_a_mcg: 75, vitamin_c_mg: 0, vitamin_d_iu: 44, vitamin_e_mg: 0.5, vitamin_k_mcg: 0.2, b12_mcg: 0.6, folate_mcg: 22, iron_mg: 0.9, calcium_mg: 25, magnesium_mg: 5, zinc_mg: 0.6, potassium_mg: 70, sodium_mg: 62 } },
  { id: '7', name: 'Greek Yogurt', serving: '1 cup (245g)', cuisine: 'north-american', mealType: 'snack', nutrients: { calories: 150, protein_g: 25, carbs_g: 6, sugars_g: 6, fiber_g: 0, fats_g: 4, saturated_fat_g: 2.5, unsaturated_fat_g: 1.5, vitamin_a_mcg: 10, vitamin_c_mg: 1, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0.5, b12_mcg: 1.2, folate_mcg: 12, iron_mg: 0.1, calcium_mg: 230, magnesium_mg: 20, zinc_mg: 1, potassium_mg: 280, sodium_mg: 60 } },
  { id: '8', name: 'Whey Protein (1 scoop)', serving: '30g', cuisine: 'north-american', mealType: 'snack', nutrients: { calories: 120, protein_g: 24, carbs_g: 3, sugars_g: 1, fiber_g: 0.5, fats_g: 1.5, saturated_fat_g: 0.5, unsaturated_fat_g: 1, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 5, iron_mg: 0.5, calcium_mg: 120, magnesium_mg: 25, zinc_mg: 0.3, potassium_mg: 100, sodium_mg: 50 } },
  { id: '10', name: 'Oats (rolled, cooked)', serving: '1 cup (240g)', cuisine: 'north-american', mealType: 'breakfast', nutrients: { calories: 166, protein_g: 6, carbs_g: 28, sugars_g: 1, fiber_g: 4, fats_g: 3.5, saturated_fat_g: 0.6, unsaturated_fat_g: 2.9, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.1, vitamin_k_mcg: 0.5, b12_mcg: 0, folate_mcg: 14, iron_mg: 1.7, calcium_mg: 20, magnesium_mg: 60, zinc_mg: 1, potassium_mg: 160, sodium_mg: 2 } },
  { id: '11', name: 'Sweet Potato (baked)', serving: '1 medium (150g)', cuisine: 'north-american', mealType: 'dinner', nutrients: { calories: 130, protein_g: 2, carbs_g: 30, sugars_g: 9, fiber_g: 4, fats_g: 0.2, saturated_fat_g: 0, unsaturated_fat_g: 0.2, vitamin_a_mcg: 1150, vitamin_c_mg: 22, vitamin_d_iu: 0, vitamin_e_mg: 0.3, vitamin_k_mcg: 3, b12_mcg: 0, folate_mcg: 18, iron_mg: 0.8, calcium_mg: 40, magnesium_mg: 30, zinc_mg: 0.4, potassium_mg: 440, sodium_mg: 70 } },
  { id: '12', name: 'Almonds', serving: '1 oz (28g)', cuisine: 'north-american', mealType: 'snack', nutrients: { calories: 164, protein_g: 6, carbs_g: 6, sugars_g: 1, fiber_g: 3.5, fats_g: 14, saturated_fat_g: 1, unsaturated_fat_g: 13, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 7.3, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 14, iron_mg: 1, calcium_mg: 76, magnesium_mg: 80, zinc_mg: 0.9, potassium_mg: 210, sodium_mg: 0 } },
  { id: '13', name: 'Spinach (cooked)', serving: '1 cup (180g)', cuisine: 'north-american', mealType: 'dinner', nutrients: { calories: 41, protein_g: 5, carbs_g: 7, sugars_g: 1, fiber_g: 4, fats_g: 0.5, saturated_fat_g: 0, unsaturated_fat_g: 0.5, vitamin_a_mcg: 940, vitamin_c_mg: 17, vitamin_d_iu: 0, vitamin_e_mg: 2, vitamin_k_mcg: 540, b12_mcg: 0, folate_mcg: 130, iron_mg: 3.6, calcium_mg: 100, magnesium_mg: 80, zinc_mg: 0.5, potassium_mg: 470, sodium_mg: 125 } },
  { id: '14', name: 'Apple', serving: '1 medium (180g)', cuisine: 'north-american', mealType: 'snack', nutrients: { calories: 95, protein_g: 0.5, carbs_g: 25, sugars_g: 19, fiber_g: 4.5, fats_g: 0.3, saturated_fat_g: 0, unsaturated_fat_g: 0.3, vitamin_a_mcg: 3, vitamin_c_mg: 8, vitamin_d_iu: 0, vitamin_e_mg: 0.2, vitamin_k_mcg: 4, b12_mcg: 0, folate_mcg: 5, iron_mg: 0.2, calcium_mg: 10, magnesium_mg: 6, zinc_mg: 0.1, potassium_mg: 195, sodium_mg: 2 } },
  { id: '15', name: 'Salmon (grilled)', serving: '150g', cuisine: 'north-american', mealType: 'dinner', nutrients: { calories: 300, protein_g: 36, carbs_g: 0, sugars_g: 0, fiber_g: 0, fats_g: 17, saturated_fat_g: 3, unsaturated_fat_g: 14, vitamin_a_mcg: 30, vitamin_c_mg: 0, vitamin_d_iu: 570, vitamin_e_mg: 1.5, vitamin_k_mcg: 0.5, b12_mcg: 3, folate_mcg: 25, iron_mg: 0.6, calcium_mg: 15, magnesium_mg: 30, zinc_mg: 0.7, potassium_mg: 450, sodium_mg: 80 } },
  { id: '16', name: 'Brown Rice (cooked)', serving: '1 cup (195g)', cuisine: 'north-american', mealType: 'lunch', nutrients: { calories: 218, protein_g: 5, carbs_g: 46, sugars_g: 0.5, fiber_g: 3.5, fats_g: 1.6, saturated_fat_g: 0.3, unsaturated_fat_g: 1.3, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.2, vitamin_k_mcg: 0.5, b12_mcg: 0, folate_mcg: 8, iron_mg: 0.8, calcium_mg: 10, magnesium_mg: 80, zinc_mg: 1, potassium_mg: 80, sodium_mg: 5 } },
  { id: 'na1', name: 'Grilled Chicken Salad', serving: '1 bowl (300g)', cuisine: 'north-american', mealType: 'lunch', nutrients: { calories: 280, protein_g: 35, carbs_g: 10, sugars_g: 4, fiber_g: 5, fats_g: 12, saturated_fat_g: 2, unsaturated_fat_g: 10, vitamin_a_mcg: 300, vitamin_c_mg: 15, vitamin_d_iu: 0, vitamin_e_mg: 1.5, vitamin_k_mcg: 100, b12_mcg: 0.5, folate_mcg: 80, iron_mg: 2, calcium_mg: 60, magnesium_mg: 40, zinc_mg: 1, potassium_mg: 500, sodium_mg: 400 } },
  { id: 'na2', name: 'Turkey Sandwich', serving: '1 sandwich (200g)', cuisine: 'north-american', mealType: 'lunch', nutrients: { calories: 350, protein_g: 28, carbs_g: 35, sugars_g: 4, fiber_g: 3, fats_g: 10, saturated_fat_g: 2.5, unsaturated_fat_g: 7.5, vitamin_a_mcg: 20, vitamin_c_mg: 2, vitamin_d_iu: 0, vitamin_e_mg: 0.3, vitamin_k_mcg: 2, b12_mcg: 0.8, folate_mcg: 30, iron_mg: 2.5, calcium_mg: 100, magnesium_mg: 25, zinc_mg: 1.2, potassium_mg: 280, sodium_mg: 750 } },
  { id: 'na3', name: 'Peanut Butter Sandwich', serving: '1 sandwich (120g)', cuisine: 'north-american', mealType: 'breakfast', nutrients: { calories: 380, protein_g: 16, carbs_g: 40, sugars_g: 12, fiber_g: 5, fats_g: 18, saturated_fat_g: 3.5, unsaturated_fat_g: 14.5, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 3, vitamin_k_mcg: 1, b12_mcg: 0, folate_mcg: 40, iron_mg: 2, calcium_mg: 60, magnesium_mg: 50, zinc_mg: 1.2, potassium_mg: 300, sodium_mg: 450 } },
  { id: 'na4', name: 'Beef Steak (grilled)', serving: '150g', cuisine: 'north-american', mealType: 'dinner', nutrients: { calories: 350, protein_g: 40, carbs_g: 0, sugars_g: 0, fiber_g: 0, fats_g: 20, saturated_fat_g: 8, unsaturated_fat_g: 12, vitamin_a_mcg: 5, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.4, vitamin_k_mcg: 1, b12_mcg: 2, folate_mcg: 10, iron_mg: 3.5, calcium_mg: 15, magnesium_mg: 25, zinc_mg: 4.5, potassium_mg: 380, sodium_mg: 70 } },
  { id: 'na5', name: 'Baked Potato (plain)', serving: '1 medium (170g)', cuisine: 'north-american', mealType: 'dinner', nutrients: { calories: 160, protein_g: 4, carbs_g: 37, sugars_g: 2, fiber_g: 4, fats_g: 0.2, saturated_fat_g: 0, unsaturated_fat_g: 0.2, vitamin_a_mcg: 2, vitamin_c_mg: 15, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 3, b12_mcg: 0, folate_mcg: 30, iron_mg: 1.5, calcium_mg: 15, magnesium_mg: 45, zinc_mg: 0.4, potassium_mg: 620, sodium_mg: 10 } },
  { id: 'na6', name: 'Scrambled Eggs', serving: '2 large (100g)', cuisine: 'north-american', mealType: 'breakfast', nutrients: { calories: 180, protein_g: 14, carbs_g: 2, sugars_g: 1, fiber_g: 0, fats_g: 13, saturated_fat_g: 4, unsaturated_fat_g: 9, vitamin_a_mcg: 200, vitamin_c_mg: 0, vitamin_d_iu: 80, vitamin_e_mg: 0.8, vitamin_k_mcg: 0.5, b12_mcg: 1.2, folate_mcg: 40, iron_mg: 1.8, calcium_mg: 50, magnesium_mg: 10, zinc_mg: 1.2, potassium_mg: 140, sodium_mg: 320 } },
  { id: 'na7', name: 'Pancakes (with syrup)', serving: '2 medium (180g)', cuisine: 'north-american', mealType: 'breakfast', nutrients: { calories: 350, protein_g: 8, carbs_g: 60, sugars_g: 22, fiber_g: 1, fats_g: 10, saturated_fat_g: 2.5, unsaturated_fat_g: 7.5, vitamin_a_mcg: 50, vitamin_c_mg: 0, vitamin_d_iu: 30, vitamin_e_mg: 0.3, vitamin_k_mcg: 0.5, b12_mcg: 0.4, folate_mcg: 30, iron_mg: 2, calcium_mg: 120, magnesium_mg: 15, zinc_mg: 0.6, potassium_mg: 120, sodium_mg: 500 } },
  { id: 'na8', name: 'Cottage Cheese Bowl', serving: '1 cup (210g)', cuisine: 'north-american', mealType: 'snack', nutrients: { calories: 180, protein_g: 24, carbs_g: 6, sugars_g: 6, fiber_g: 0, fats_g: 5, saturated_fat_g: 3, unsaturated_fat_g: 2, vitamin_a_mcg: 50, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0.5, b12_mcg: 1, folate_mcg: 10, iron_mg: 0.2, calcium_mg: 140, magnesium_mg: 10, zinc_mg: 0.6, potassium_mg: 120, sodium_mg: 400 } },
  { id: 'na9', name: 'Tuna Salad Wrap', serving: '1 wrap (250g)', cuisine: 'north-american', mealType: 'lunch', nutrients: { calories: 400, protein_g: 32, carbs_g: 30, sugars_g: 3, fiber_g: 3, fats_g: 16, saturated_fat_g: 3, unsaturated_fat_g: 13, vitamin_a_mcg: 40, vitamin_c_mg: 5, vitamin_d_iu: 80, vitamin_e_mg: 1.2, vitamin_k_mcg: 5, b12_mcg: 2, folate_mcg: 35, iron_mg: 2, calcium_mg: 80, magnesium_mg: 20, zinc_mg: 0.8, potassium_mg: 300, sodium_mg: 650 } },
  { id: 'na10', name: 'Protein Pancakes', serving: '2 medium (160g)', cuisine: 'north-american', mealType: 'breakfast', nutrients: { calories: 280, protein_g: 24, carbs_g: 30, sugars_g: 5, fiber_g: 3, fats_g: 6, saturated_fat_g: 1.5, unsaturated_fat_g: 4.5, vitamin_a_mcg: 30, vitamin_c_mg: 0, vitamin_d_iu: 20, vitamin_e_mg: 0.3, vitamin_k_mcg: 0.5, b12_mcg: 0.4, folate_mcg: 25, iron_mg: 1.5, calcium_mg: 100, magnesium_mg: 20, zinc_mg: 0.8, potassium_mg: 150, sodium_mg: 350 } },
  { id: 'na11', name: 'Mixed Nuts', serving: '1/4 cup (30g)', cuisine: 'north-american', mealType: 'snack', nutrients: { calories: 180, protein_g: 5, carbs_g: 6, sugars_g: 2, fiber_g: 3, fats_g: 16, saturated_fat_g: 2, unsaturated_fat_g: 14, vitamin_a_mcg: 5, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 4, vitamin_k_mcg: 1, b12_mcg: 0, folate_mcg: 15, iron_mg: 1, calcium_mg: 30, magnesium_mg: 60, zinc_mg: 1, potassium_mg: 150, sodium_mg: 0 } },
  { id: 'na12', name: 'Turkey & Avocado Wrap', serving: '1 wrap (260g)', cuisine: 'north-american', mealType: 'lunch', nutrients: { calories: 420, protein_g: 30, carbs_g: 28, sugars_g: 2, fiber_g: 6, fats_g: 22, saturated_fat_g: 4, unsaturated_fat_g: 18, vitamin_a_mcg: 50, vitamin_c_mg: 8, vitamin_d_iu: 0, vitamin_e_mg: 2, vitamin_k_mcg: 15, b12_mcg: 0.6, folate_mcg: 45, iron_mg: 2, calcium_mg: 80, magnesium_mg: 35, zinc_mg: 1.2, potassium_mg: 450, sodium_mg: 600 } },
  { id: 'na13', name: 'Beef Chili', serving: '1 cup (250g)', cuisine: 'north-american', mealType: 'dinner', nutrients: { calories: 330, protein_g: 28, carbs_g: 28, sugars_g: 5, fiber_g: 8, fats_g: 12, saturated_fat_g: 4, unsaturated_fat_g: 8, vitamin_a_mcg: 200, vitamin_c_mg: 15, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 6, b12_mcg: 1.5, folate_mcg: 40, iron_mg: 4, calcium_mg: 40, magnesium_mg: 45, zinc_mg: 3, potassium_mg: 500, sodium_mg: 700 } },
  { id: 'na14', name: 'Veggie Burger (patty only)', serving: '1 patty (100g)', cuisine: 'north-american', mealType: 'dinner', nutrients: { calories: 180, protein_g: 14, carbs_g: 14, sugars_g: 2, fiber_g: 5, fats_g: 8, saturated_fat_g: 1, unsaturated_fat_g: 7, vitamin_a_mcg: 100, vitamin_c_mg: 5, vitamin_d_iu: 0, vitamin_e_mg: 1, vitamin_k_mcg: 8, b12_mcg: 0.5, folate_mcg: 30, iron_mg: 2.5, calcium_mg: 40, magnesium_mg: 30, zinc_mg: 1.2, potassium_mg: 250, sodium_mg: 350 } },
  { id: 'na15', name: 'Protein Smoothie', serving: '1 glass (300ml)', cuisine: 'north-american', mealType: 'snack', nutrients: { calories: 220, protein_g: 25, carbs_g: 25, sugars_g: 15, fiber_g: 3, fats_g: 4, saturated_fat_g: 1, unsaturated_fat_g: 3, vitamin_a_mcg: 100, vitamin_c_mg: 30, vitamin_d_iu: 50, vitamin_e_mg: 0.8, vitamin_k_mcg: 5, b12_mcg: 0.8, folate_mcg: 20, iron_mg: 0.5, calcium_mg: 200, magnesium_mg: 30, zinc_mg: 0.5, potassium_mg: 350, sodium_mg: 100 } },
];

const EAST_ASIAN_FOODS: FoodItem[] = [
  { id: '6', name: 'Banana', serving: '1 medium (120g)', cuisine: 'east-asian', mealType: 'snack', nutrients: { calories: 105, protein_g: 1, carbs_g: 27, sugars_g: 14, fiber_g: 3, fats_g: 0.4, saturated_fat_g: 0.1, unsaturated_fat_g: 0.3, vitamin_a_mcg: 4, vitamin_c_mg: 10, vitamin_d_iu: 0, vitamin_e_mg: 0.1, vitamin_k_mcg: 0.6, b12_mcg: 0, folate_mcg: 24, iron_mg: 0.3, calcium_mg: 6, magnesium_mg: 32, zinc_mg: 0.2, potassium_mg: 422, sodium_mg: 1 } },
  { id: 'ea1', name: 'Steamed Rice (jasmine)', serving: '1 cup (160g)', cuisine: 'east-asian', mealType: 'lunch', nutrients: { calories: 200, protein_g: 4, carbs_g: 44, sugars_g: 0, fiber_g: 0.5, fats_g: 0.4, saturated_fat_g: 0.1, unsaturated_fat_g: 0.3, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 70, iron_mg: 1.5, calcium_mg: 8, magnesium_mg: 10, zinc_mg: 0.4, potassium_mg: 45, sodium_mg: 1 } },
  { id: 'ea2', name: 'Teriyaki Chicken', serving: '1 serving (200g)', cuisine: 'east-asian', mealType: 'dinner', nutrients: { calories: 320, protein_g: 30, carbs_g: 18, sugars_g: 12, fiber_g: 0.5, fats_g: 12, saturated_fat_g: 3, unsaturated_fat_g: 9, vitamin_a_mcg: 10, vitamin_c_mg: 2, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 1, b12_mcg: 0.5, folate_mcg: 8, iron_mg: 1.5, calcium_mg: 20, magnesium_mg: 25, zinc_mg: 1, potassium_mg: 300, sodium_mg: 850 } },
  { id: 'ea3', name: 'Miso Soup', serving: '1 bowl (200ml)', cuisine: 'east-asian', mealType: 'lunch', nutrients: { calories: 40, protein_g: 3, carbs_g: 4, sugars_g: 1, fiber_g: 1, fats_g: 1, saturated_fat_g: 0.2, unsaturated_fat_g: 0.8, vitamin_a_mcg: 10, vitamin_c_mg: 1, vitamin_d_iu: 0, vitamin_e_mg: 0.1, vitamin_k_mcg: 2, b12_mcg: 0.1, folate_mcg: 15, iron_mg: 0.8, calcium_mg: 25, magnesium_mg: 10, zinc_mg: 0.4, potassium_mg: 120, sodium_mg: 700 } },
  { id: 'ea4', name: 'Sushi Roll (maki)', serving: '6 pieces (180g)', cuisine: 'east-asian', mealType: 'lunch', nutrients: { calories: 250, protein_g: 10, carbs_g: 40, sugars_g: 4, fiber_g: 2, fats_g: 5, saturated_fat_g: 1, unsaturated_fat_g: 4, vitamin_a_mcg: 30, vitamin_c_mg: 3, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 8, b12_mcg: 0.6, folate_mcg: 20, iron_mg: 1, calcium_mg: 20, magnesium_mg: 25, zinc_mg: 0.5, potassium_mg: 180, sodium_mg: 500 } },
  { id: 'ea5', name: 'Stir-Fried Bok Choy', serving: '1 cup (150g)', cuisine: 'east-asian', mealType: 'dinner', nutrients: { calories: 30, protein_g: 2, carbs_g: 3, sugars_g: 1, fiber_g: 2, fats_g: 1.5, saturated_fat_g: 0.2, unsaturated_fat_g: 1.3, vitamin_a_mcg: 250, vitamin_c_mg: 35, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 80, b12_mcg: 0, folate_mcg: 40, iron_mg: 1, calcium_mg: 80, magnesium_mg: 15, zinc_mg: 0.2, potassium_mg: 250, sodium_mg: 300 } },
  { id: 'ea6', name: 'Edamame (steamed)', serving: '1 cup (150g)', cuisine: 'east-asian', mealType: 'snack', nutrients: { calories: 190, protein_g: 17, carbs_g: 14, sugars_g: 3, fiber_g: 8, fats_g: 8, saturated_fat_g: 1, unsaturated_fat_g: 7, vitamin_a_mcg: 15, vitamin_c_mg: 6, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 25, b12_mcg: 0, folate_mcg: 120, iron_mg: 3.5, calcium_mg: 60, magnesium_mg: 50, zinc_mg: 1.2, potassium_mg: 500, sodium_mg: 10 } },
  { id: 'ea7', name: 'Japanese Sweet Potato', serving: '1 medium (150g)', cuisine: 'east-asian', mealType: 'lunch', nutrients: { calories: 140, protein_g: 2, carbs_g: 32, sugars_g: 10, fiber_g: 4, fats_g: 0.2, saturated_fat_g: 0, unsaturated_fat_g: 0.2, vitamin_a_mcg: 1400, vitamin_c_mg: 20, vitamin_d_iu: 0, vitamin_e_mg: 0.4, vitamin_k_mcg: 3, b12_mcg: 0, folate_mcg: 15, iron_mg: 0.7, calcium_mg: 30, magnesium_mg: 25, zinc_mg: 0.3, potassium_mg: 380, sodium_mg: 50 } },
  { id: 'ea8', name: 'Tofu (firm, stir-fried)', serving: '150g', cuisine: 'east-asian', mealType: 'dinner', nutrients: { calories: 180, protein_g: 18, carbs_g: 5, sugars_g: 1, fiber_g: 2, fats_g: 10, saturated_fat_g: 1.5, unsaturated_fat_g: 8.5, vitamin_a_mcg: 50, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.2, vitamin_k_mcg: 3, b12_mcg: 0, folate_mcg: 30, iron_mg: 3, calcium_mg: 200, magnesium_mg: 35, zinc_mg: 1, potassium_mg: 180, sodium_mg: 100 } },
  { id: 'ea9', name: 'Ramen (shoyu)', serving: '1 bowl (500g)', cuisine: 'east-asian', mealType: 'dinner', nutrients: { calories: 450, protein_g: 18, carbs_g: 55, sugars_g: 3, fiber_g: 2, fats_g: 18, saturated_fat_g: 6, unsaturated_fat_g: 12, vitamin_a_mcg: 30, vitamin_c_mg: 2, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 3, b12_mcg: 0.4, folate_mcg: 35, iron_mg: 2.5, calcium_mg: 30, magnesium_mg: 20, zinc_mg: 1, potassium_mg: 200, sodium_mg: 1200 } },
  { id: 'ea10', name: 'Seaweed Salad', serving: '1 cup (100g)', cuisine: 'east-asian', mealType: 'lunch', nutrients: { calories: 45, protein_g: 2, carbs_g: 6, sugars_g: 1, fiber_g: 3, fats_g: 1.5, saturated_fat_g: 0.3, unsaturated_fat_g: 1.2, vitamin_a_mcg: 200, vitamin_c_mg: 3, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 40, b12_mcg: 0, folate_mcg: 40, iron_mg: 1.5, calcium_mg: 50, magnesium_mg: 40, zinc_mg: 0.5, potassium_mg: 300, sodium_mg: 400 } },
  { id: 'ea11', name: 'Chicken Katsu', serving: '1 serving (180g)', cuisine: 'east-asian', mealType: 'dinner', nutrients: { calories: 400, protein_g: 28, carbs_g: 22, sugars_g: 2, fiber_g: 1, fats_g: 22, saturated_fat_g: 5, unsaturated_fat_g: 17, vitamin_a_mcg: 10, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 1, vitamin_k_mcg: 1, b12_mcg: 0.5, folate_mcg: 10, iron_mg: 1.5, calcium_mg: 20, magnesium_mg: 30, zinc_mg: 1, potassium_mg: 300, sodium_mg: 600 } },
  { id: 'ea12', name: 'Kimchi', serving: '1/2 cup (80g)', cuisine: 'east-asian', mealType: 'lunch', nutrients: { calories: 20, protein_g: 1, carbs_g: 3, sugars_g: 1, fiber_g: 2, fats_g: 0.5, saturated_fat_g: 0, unsaturated_fat_g: 0.5, vitamin_a_mcg: 100, vitamin_c_mg: 10, vitamin_d_iu: 0, vitamin_e_mg: 0.2, vitamin_k_mcg: 20, b12_mcg: 0, folate_mcg: 20, iron_mg: 1.5, calcium_mg: 20, magnesium_mg: 10, zinc_mg: 0.3, potassium_mg: 120, sodium_mg: 500 } },
  { id: 'ea13', name: 'Bibimbap (without egg)', serving: '1 bowl (400g)', cuisine: 'east-asian', mealType: 'lunch', nutrients: { calories: 450, protein_g: 16, carbs_g: 70, sugars_g: 5, fiber_g: 5, fats_g: 12, saturated_fat_g: 2, unsaturated_fat_g: 10, vitamin_a_mcg: 250, vitamin_c_mg: 15, vitamin_d_iu: 0, vitamin_e_mg: 1, vitamin_k_mcg: 30, b12_mcg: 0.3, folate_mcg: 60, iron_mg: 2.5, calcium_mg: 50, magnesium_mg: 40, zinc_mg: 1.2, potassium_mg: 400, sodium_mg: 600 } },
  { id: 'ea14', name: 'Mochi (rice cake)', serving: '2 pieces (80g)', cuisine: 'east-asian', mealType: 'snack', nutrients: { calories: 180, protein_g: 3, carbs_g: 40, sugars_g: 8, fiber_g: 1, fats_g: 1, saturated_fat_g: 0.2, unsaturated_fat_g: 0.8, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 5, iron_mg: 0.5, calcium_mg: 5, magnesium_mg: 5, zinc_mg: 0.2, potassium_mg: 20, sodium_mg: 5 } },
  { id: 'ea15', name: 'Grilled Mackerel', serving: '1 fillet (120g)', cuisine: 'east-asian', mealType: 'dinner', nutrients: { calories: 260, protein_g: 22, carbs_g: 0, sugars_g: 0, fiber_g: 0, fats_g: 18, saturated_fat_g: 4, unsaturated_fat_g: 14, vitamin_a_mcg: 40, vitamin_c_mg: 0, vitamin_d_iu: 400, vitamin_e_mg: 1.5, vitamin_k_mcg: 2, b12_mcg: 4, folate_mcg: 5, iron_mg: 1.2, calcium_mg: 20, magnesium_mg: 30, zinc_mg: 0.6, potassium_mg: 350, sodium_mg: 80 } },
];

const SOUTHEAST_ASIAN_FOODS: FoodItem[] = [
  { id: 'sea1', name: 'Pad Thai', serving: '1 plate (300g)', cuisine: 'southeast-asian', mealType: 'dinner', nutrients: { calories: 420, protein_g: 12, carbs_g: 55, sugars_g: 10, fiber_g: 3, fats_g: 18, saturated_fat_g: 4, unsaturated_fat_g: 14, vitamin_a_mcg: 50, vitamin_c_mg: 5, vitamin_d_iu: 0, vitamin_e_mg: 1.5, vitamin_k_mcg: 5, b12_mcg: 0.3, folate_mcg: 50, iron_mg: 2, calcium_mg: 30, magnesium_mg: 35, zinc_mg: 1, potassium_mg: 250, sodium_mg: 800 } },
  { id: 'sea2', name: 'Tom Yum Soup', serving: '1 bowl (250ml)', cuisine: 'southeast-asian', mealType: 'lunch', nutrients: { calories: 120, protein_g: 8, carbs_g: 6, sugars_g: 3, fiber_g: 1, fats_g: 7, saturated_fat_g: 5, unsaturated_fat_g: 2, vitamin_a_mcg: 60, vitamin_c_mg: 10, vitamin_d_iu: 0, vitamin_e_mg: 0.3, vitamin_k_mcg: 3, b12_mcg: 0.4, folate_mcg: 15, iron_mg: 1, calcium_mg: 20, magnesium_mg: 15, zinc_mg: 0.5, potassium_mg: 220, sodium_mg: 700 } },
  { id: 'sea3', name: 'Green Curry (chicken)', serving: '1 cup (250g)', cuisine: 'southeast-asian', mealType: 'dinner', nutrients: { calories: 300, protein_g: 22, carbs_g: 8, sugars_g: 3, fiber_g: 2, fats_g: 20, saturated_fat_g: 14, unsaturated_fat_g: 6, vitamin_a_mcg: 100, vitamin_c_mg: 8, vitamin_d_iu: 0, vitamin_e_mg: 0.8, vitamin_k_mcg: 5, b12_mcg: 0.4, folate_mcg: 20, iron_mg: 1.5, calcium_mg: 40, magnesium_mg: 30, zinc_mg: 1, potassium_mg: 320, sodium_mg: 650 } },
  { id: 'sea4', name: 'Vietnamese Pho (beef)', serving: '1 bowl (500g)', cuisine: 'southeast-asian', mealType: 'lunch', nutrients: { calories: 380, protein_g: 24, carbs_g: 50, sugars_g: 3, fiber_g: 2, fats_g: 10, saturated_fat_g: 3.5, unsaturated_fat_g: 6.5, vitamin_a_mcg: 20, vitamin_c_mg: 2, vitamin_d_iu: 0, vitamin_e_mg: 0.3, vitamin_k_mcg: 2, b12_mcg: 1.5, folate_mcg: 35, iron_mg: 3, calcium_mg: 30, magnesium_mg: 25, zinc_mg: 2, potassium_mg: 350, sodium_mg: 900 } },
  { id: 'sea5', name: 'Spring Rolls (fresh)', serving: '2 rolls (120g)', cuisine: 'southeast-asian', mealType: 'lunch', nutrients: { calories: 120, protein_g: 6, carbs_g: 16, sugars_g: 3, fiber_g: 3, fats_g: 3, saturated_fat_g: 0.5, unsaturated_fat_g: 2.5, vitamin_a_mcg: 150, vitamin_c_mg: 10, vitamin_d_iu: 0, vitamin_e_mg: 0.4, vitamin_k_mcg: 20, b12_mcg: 0.1, folate_mcg: 25, iron_mg: 1, calcium_mg: 30, magnesium_mg: 15, zinc_mg: 0.4, potassium_mg: 180, sodium_mg: 250 } },
  { id: 'sea6', name: 'Nasi Goreng', serving: '1 plate (350g)', cuisine: 'southeast-asian', mealType: 'dinner', nutrients: { calories: 400, protein_g: 14, carbs_g: 55, sugars_g: 5, fiber_g: 2, fats_g: 14, saturated_fat_g: 3, unsaturated_fat_g: 11, vitamin_a_mcg: 80, vitamin_c_mg: 4, vitamin_d_iu: 0, vitamin_e_mg: 1, vitamin_k_mcg: 5, b12_mcg: 0.4, folate_mcg: 30, iron_mg: 2, calcium_mg: 20, magnesium_mg: 25, zinc_mg: 0.8, potassium_mg: 250, sodium_mg: 750 } },
  { id: 'sea7', name: 'Mango Sticky Rice', serving: '1 serving (200g)', cuisine: 'southeast-asian', mealType: 'snack', nutrients: { calories: 350, protein_g: 4, carbs_g: 60, sugars_g: 30, fiber_g: 2, fats_g: 12, saturated_fat_g: 8, unsaturated_fat_g: 4, vitamin_a_mcg: 150, vitamin_c_mg: 20, vitamin_d_iu: 0, vitamin_e_mg: 0.5, vitamin_k_mcg: 2, b12_mcg: 0, folate_mcg: 20, iron_mg: 1, calcium_mg: 40, magnesium_mg: 20, zinc_mg: 0.3, potassium_mg: 200, sodium_mg: 50 } },
  { id: 'sea8', name: 'Larb (chicken)', serving: '1 cup (180g)', cuisine: 'southeast-asian', mealType: 'dinner', nutrients: { calories: 220, protein_g: 24, carbs_g: 6, sugars_g: 2, fiber_g: 2, fats_g: 11, saturated_fat_g: 3, unsaturated_fat_g: 8, vitamin_a_mcg: 30, vitamin_c_mg: 6, vitamin_d_iu: 0, vitamin_e_mg: 0.4, vitamin_k_mcg: 4, b12_mcg: 0.4, folate_mcg: 15, iron_mg: 1.5, calcium_mg: 25, magnesium_mg: 20, zinc_mg: 1, potassium_mg: 280, sodium_mg: 550 } },
  { id: 'sea9', name: 'Satay Skewers (chicken)', serving: '4 skewers (120g)', cuisine: 'southeast-asian', mealType: 'dinner', nutrients: { calories: 260, protein_g: 28, carbs_g: 6, sugars_g: 4, fiber_g: 1, fats_g: 14, saturated_fat_g: 3.5, unsaturated_fat_g: 10.5, vitamin_a_mcg: 10, vitamin_c_mg: 1, vitamin_d_iu: 0, vitamin_e_mg: 0.8, vitamin_k_mcg: 1, b12_mcg: 0.4, folate_mcg: 10, iron_mg: 1.2, calcium_mg: 15, magnesium_mg: 25, zinc_mg: 0.8, potassium_mg: 250, sodium_mg: 500 } },
  { id: 'sea10', name: 'Som Tam (papaya salad)', serving: '1 cup (150g)', cuisine: 'southeast-asian', mealType: 'lunch', nutrients: { calories: 80, protein_g: 2, carbs_g: 15, sugars_g: 8, fiber_g: 3, fats_g: 2, saturated_fat_g: 0.3, unsaturated_fat_g: 1.7, vitamin_a_mcg: 300, vitamin_c_mg: 50, vitamin_d_iu: 0, vitamin_e_mg: 0.6, vitamin_k_mcg: 30, b12_mcg: 0, folate_mcg: 30, iron_mg: 0.5, calcium_mg: 30, magnesium_mg: 15, zinc_mg: 0.3, potassium_mg: 250, sodium_mg: 600 } },
  { id: 'sea11', name: 'Beef Rendang', serving: '1 cup (200g)', cuisine: 'southeast-asian', mealType: 'dinner', nutrients: { calories: 380, protein_g: 26, carbs_g: 8, sugars_g: 3, fiber_g: 2, fats_g: 27, saturated_fat_g: 12, unsaturated_fat_g: 15, vitamin_a_mcg: 40, vitamin_c_mg: 2, vitamin_d_iu: 0, vitamin_e_mg: 0.6, vitamin_k_mcg: 3, b12_mcg: 1.8, folate_mcg: 15, iron_mg: 3.5, calcium_mg: 30, magnesium_mg: 30, zinc_mg: 3, potassium_mg: 350, sodium_mg: 550 } },
  { id: 'sea12', name: 'Coconut Rice', serving: '1 cup (180g)', cuisine: 'southeast-asian', mealType: 'lunch', nutrients: { calories: 280, protein_g: 4, carbs_g: 40, sugars_g: 2, fiber_g: 1, fats_g: 12, saturated_fat_g: 10, unsaturated_fat_g: 2, vitamin_a_mcg: 0, vitamin_c_mg: 0, vitamin_d_iu: 0, vitamin_e_mg: 0.1, vitamin_k_mcg: 0.5, b12_mcg: 0, folate_mcg: 60, iron_mg: 1.5, calcium_mg: 15, magnesium_mg: 15, zinc_mg: 0.5, potassium_mg: 80, sodium_mg: 5 } },
  { id: 'sea13', name: 'Pork Dumplings (steamed)', serving: '6 pieces (150g)', cuisine: 'southeast-asian', mealType: 'lunch', nutrients: { calories: 280, protein_g: 16, carbs_g: 30, sugars_g: 2, fiber_g: 2, fats_g: 10, saturated_fat_g: 3, unsaturated_fat_g: 7, vitamin_a_mcg: 20, vitamin_c_mg: 1, vitamin_d_iu: 0, vitamin_e_mg: 0.3, vitamin_k_mcg: 2, b12_mcg: 0.5, folate_mcg: 15, iron_mg: 2, calcium_mg: 20, magnesium_mg: 15, zinc_mg: 1.2, potassium_mg: 180, sodium_mg: 600 } },
  { id: 'sea14', name: 'Thai Basil Chicken (Pad Krapow)', serving: '1 serving (200g)', cuisine: 'southeast-asian', mealType: 'dinner', nutrients: { calories: 290, protein_g: 26, carbs_g: 8, sugars_g: 3, fiber_g: 2, fats_g: 17, saturated_fat_g: 4, unsaturated_fat_g: 13, vitamin_a_mcg: 80, vitamin_c_mg: 8, vitamin_d_iu: 0, vitamin_e_mg: 0.8, vitamin_k_mcg: 40, b12_mcg: 0.4, folate_mcg: 15, iron_mg: 1.5, calcium_mg: 25, magnesium_mg: 25, zinc_mg: 1, potassium_mg: 300, sodium_mg: 700 } },
  { id: 'sea15', name: 'Fresh Coconut Water', serving: '1 cup (240ml)', cuisine: 'southeast-asian', mealType: 'snack', nutrients: { calories: 45, protein_g: 0, carbs_g: 9, sugars_g: 6, fiber_g: 0, fats_g: 0.5, saturated_fat_g: 0.4, unsaturated_fat_g: 0.1, vitamin_a_mcg: 0, vitamin_c_mg: 2, vitamin_d_iu: 0, vitamin_e_mg: 0, vitamin_k_mcg: 0, b12_mcg: 0, folate_mcg: 5, iron_mg: 0.3, calcium_mg: 20, magnesium_mg: 15, zinc_mg: 0.1, potassium_mg: 250, sodium_mg: 60 } },
];

export const COMMON_FOODS: FoodItem[] = [
  ...INDIAN_FOODS,
  ...NORTH_AMERICAN_FOODS,
  ...EAST_ASIAN_FOODS,
  ...SOUTHEAST_ASIAN_FOODS,
];
