import { ExerciseBiomechanics } from "../../types";

// ────────────────────────────────────────────────────────────
// 1. PISTOL SQUAT (Single Leg Squat)
// ────────────────────────────────────────────────────────────
export const pistolSquat: ExerciseBiomechanics = {
  id: "pistol-squat",
  name: "Pistol Squat",
  aliases: ["Single Leg Squat", "Pistol"],
  category: "legs",
  description: "Unilateral squat on one leg with the opposite leg extended forward. Requires significant strength, mobility, and balance.",
  tags: ["legs", "quads", "glutes", "hamstrings", "balance", "unilateral", "advanced"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex", "leftHeel", "rightHeel", "leftEar", "rightEar"],
  checkpoints: [
    {
      id: "pistol-knee-angle-bottom-l", name: "Standing Knee Angle (Left)",
      description: "Knee flexion of the left standing leg at the bottom of the pistol squat.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [60, 90], warningRange: [90, 110], criticalRange: [110, 180],
      side: "left", phase: "Bottom", weight: 10,
      cueGood: "Full pistol depth achieved", cueWarning: "Bend knee deeper — aim for <90°", cueCritical: "Knee barely bent — lower much more",
    },
    {
      id: "pistol-knee-angle-bottom-r", name: "Standing Knee Angle (Right)",
      description: "Knee flexion of the right standing leg at the bottom of the pistol squat.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [60, 90], warningRange: [90, 110], criticalRange: [110, 180],
      side: "right", phase: "Bottom", weight: 10,
      cueGood: "Full pistol depth achieved", cueWarning: "Bend knee deeper — aim for <90°", cueCritical: "Knee barely bent — lower much more",
    },
    {
      id: "pistol-hip-flexion-bottom-l", name: "Standing Hip Flexion (Left)",
      description: "Hip flexion of the left standing leg at the bottom position.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [50, 90], warningRange: [90, 120], criticalRange: [120, 180],
      side: "left", phase: "Bottom", weight: 8,
      cueGood: "Hip fully engaged at depth", cueWarning: "Increase hip flexion — fold deeper", cueCritical: "Hip barely flexed — sit back and down more",
    },
    {
      id: "pistol-hip-flexion-bottom-r", name: "Standing Hip Flexion (Right)",
      description: "Hip flexion of the right standing leg at the bottom position.",
      angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "rightKnee" },
      goodRange: [50, 90], warningRange: [90, 120], criticalRange: [120, 180],
      side: "right", phase: "Bottom", weight: 8,
      cueGood: "Hip fully engaged at depth", cueWarning: "Increase hip flexion — fold deeper", cueCritical: "Hip barely flexed — sit back and down more",
    },
    {
      id: "pistol-nonworking-leg-r", name: "Non-Working Leg Extension (Right)",
      description: "The right leg should be extended forward with minimal knee bend when the left leg is working.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [160, 180], warningRange: [140, 160], criticalRange: [0, 140],
      side: "right", phase: "Bottom", weight: 5,
      cueGood: "Non-working leg extended", cueWarning: "Straighten the extended leg more", cueCritical: "Extended leg too bent — reach forward",
    },
    {
      id: "pistol-nonworking-leg-l", name: "Non-Working Leg Extension (Left)",
      description: "The left leg should be extended forward with minimal knee bend when the right leg is working.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [160, 180], warningRange: [140, 160], criticalRange: [0, 140],
      side: "left", phase: "Bottom", weight: 5,
      cueGood: "Non-working leg extended", cueWarning: "Straighten the extended leg more", cueCritical: "Extended leg too bent — reach forward",
    },
    {
      id: "pistol-trunk-lean", name: "Trunk Lean Forward",
      description: "Torso lean angle relative to vertical. Excessive forward lean shifts load to the lower back.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [55, 85], warningRange: [85, 105], criticalRange: [105, 180],
      side: "both", phase: "Bottom", weight: 7,
      cueGood: "Upright torso with slight forward lean", cueWarning: "Chest dropping — keep torso tall", cueCritical: "Excessive forward lean — engage core and keep chest up",
    },
    {
      id: "pistol-ankle-dorsiflexion-l", name: "Ankle Dorsiflexion (Left)",
      description: "Ankle dorsiflexion of the left standing leg. Adequate mobility allows knee-over-toe without heel lift.",
      angle: { joint: "leftAnkle", p1: "leftKnee", p2: "leftAnkle", p3: "leftFootIndex" },
      goodRange: [78, 100], warningRange: [60, 78], criticalRange: [0, 60],
      side: "left", phase: "Bottom", weight: 6,
      cueGood: "Ankle mobility adequate for depth", cueWarning: "Limited dorsiflexion — elevate heel or improve mobility", cueCritical: "Severe ankle restriction — heel likely lifting",
    },
    {
      id: "pistol-ankle-dorsiflexion-r", name: "Ankle Dorsiflexion (Right)",
      description: "Ankle dorsiflexion of the right standing leg.",
      angle: { joint: "rightAnkle", p1: "rightKnee", p2: "rightAnkle", p3: "rightFootIndex" },
      goodRange: [78, 100], warningRange: [60, 78], criticalRange: [0, 60],
      side: "right", phase: "Bottom", weight: 6,
      cueGood: "Ankle mobility adequate for depth", cueWarning: "Limited dorsiflexion — elevate heel or improve mobility", cueCritical: "Severe ankle restriction — heel likely lifting",
    },
    {
      id: "pistol-knee-tracking-l", name: "Knee Tracking Over Foot (Left)",
      description: "Frontal-plane knee alignment relative to the foot. Knee should track over the second toe.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftFootIndex" },
      goodRange: [165, 180], warningRange: [155, 165], criticalRange: [0, 155],
      side: "left", phase: "Descent", weight: 9,
      cueGood: "Knee tracking properly over the foot",
      cueWarning: "Knee drifting inward — push the knee out toward the pinky toe",
      cueCritical: "Knee collapsing inward — high valgus stress. Push knee out",
    },
    {
      id: "pistol-knee-tracking-r", name: "Knee Tracking Over Foot (Right)",
      description: "Frontal-plane knee alignment of the right leg relative to the foot.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightFootIndex" },
      goodRange: [165, 180], warningRange: [155, 165], criticalRange: [0, 155],
      side: "right", phase: "Descent", weight: 9,
      cueGood: "Knee tracking properly over the foot",
      cueWarning: "Knee drifting inward — push the knee out toward the pinky toe",
      cueCritical: "Knee collapsing inward — high valgus stress. Push knee out",
    },
  ],
  phases: [
    { name: "Setup", description: "Stand on one leg, extend the other forward at hip height, arms out for balance." },
    { name: "Descent", description: "Bend the standing knee and hinge at the hip while keeping the non-working leg elevated." },
    { name: "Bottom", description: "Deepest position with the standing thigh past parallel; non-working leg extended forward." },
    { name: "Ascent", description: "Drive through the full foot of the standing leg to return upright." },
    { name: "Lockout", description: "Full hip and knee extension with balance control." },
  ],
};

// ────────────────────────────────────────────────────────────
// 2. ROMANIAN DEADLIFT (Both Legs + Single Leg)
// ────────────────────────────────────────────────────────────
export const romanianDeadlift: ExerciseBiomechanics = {
  id: "romanian-deadlift",
  name: "Romanian Deadlift",
  aliases: ["RDL", "Stiff Leg Deadlift", "Hip Hinge"],
  category: "legs",
  description: "Hip-hinge dominant movement targeting the posterior chain. Includes both bilateral and single-leg variations.",
  tags: ["legs", "hamstrings", "glutes", "posterior-chain", "hip-hinge", "bilateral", "unilateral"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex", "leftHeel", "rightHeel", "leftEar", "rightEar"],
  checkpoints: [
    {
      id: "rdl-hip-hinge-bilateral", name: "Hip Hinge Angle (Bottom)",
      description: "Hip angle at the bottom of the bilateral RDL. Torso should be near parallel to the ground with a neutral spine.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [85, 110], warningRange: [110, 135], criticalRange: [135, 180],
      side: "both", phase: "Bottom", weight: 10,
      cueGood: "Hinge depth achieved — torso near parallel", cueWarning: "Not hinging deep enough — push hips farther back", cueCritical: "Insufficient hip hinge — hinge at the hips, not the knees",
    },
    {
      id: "rdl-hip-hinge-single-l", name: "Hip Hinge Single Leg (Left Stance)",
      description: "Hip hinge depth on the left stance leg during a single-leg RDL.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [70, 100], warningRange: [100, 130], criticalRange: [130, 180],
      side: "left", phase: "Bottom", weight: 9,
      cueGood: "Good hinge depth on stance leg", cueWarning: "Not hinging deep enough — push hips back", cueCritical: "Stance leg not engaging — hinge deeper",
    },
    {
      id: "rdl-hip-hinge-single-r", name: "Hip Hinge Single Leg (Right Stance)",
      description: "Hip hinge depth on the right stance leg during a single-leg RDL.",
      angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "rightKnee" },
      goodRange: [70, 100], warningRange: [100, 130], criticalRange: [130, 180],
      side: "right", phase: "Bottom", weight: 9,
      cueGood: "Good hinge depth on stance leg", cueWarning: "Not hinging deep enough — push hips back", cueCritical: "Stance leg not engaging — hinge deeper",
    },
    {
      id: "rdl-spine-neutrality", name: "Spine Neutrality",
      description: "Upper back and neck alignment. The spine must remain neutral — no rounding of the lower or upper back throughout the movement.",
      angle: { joint: "leftShoulder", p1: "leftEar", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [155, 180], warningRange: [135, 155], criticalRange: [0, 135],
      side: "both", phase: "Hinge", weight: 10,
      cueGood: "Neutral spine maintained", cueWarning: "Upper back beginning to round — chest up, shoulders back", cueCritical: "Spine severely rounded — stop and reset. Hinge at hips",
    },
    {
      id: "rdl-knee-angle-l", name: "Knee Angle (Left)",
      description: "The knee should maintain a slight bend of ~10-20° throughout the RDL. Locking out or excessive bending shifts load away from the hamstrings.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [160, 175], warningRange: [175, 180], criticalRange: [0, 160],
      side: "left", phase: "Hinge", weight: 6,
      cueGood: "Knee position optimal — slight bend maintained", cueWarning: "Knee too straight — unlock slightly", cueCritical: "Knee over-bent — keep the shin vertical",
    },
    {
      id: "rdl-knee-angle-r", name: "Knee Angle (Right)",
      description: "Knee angle for the right leg during the RDL.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [160, 175], warningRange: [175, 180], criticalRange: [0, 160],
      side: "right", phase: "Hinge", weight: 6,
      cueGood: "Knee position optimal — slight bend maintained", cueWarning: "Knee too straight — unlock slightly", cueCritical: "Knee over-bent — keep the shin vertical",
    },
    {
      id: "rdl-shoulder-position-l", name: "Shoulder Position (Left)",
      description: "Shoulder position relative to the torso. Shoulders should remain retracted and neutral — not rounded forward or shrugged.",
      angle: { joint: "leftShoulder", p1: "leftElbow", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [60, 100], warningRange: [40, 60], criticalRange: [0, 40],
      side: "left", phase: "Setup", weight: 5,
      cueGood: "Shoulders neutral and retracted", cueWarning: "Shoulders rounding forward — pull them back", cueCritical: "Shoulders severely protracted — retract and stabilize",
    },
    {
      id: "rdl-shoulder-position-r", name: "Shoulder Position (Right)",
      description: "Shoulder position for the right side.",
      angle: { joint: "rightShoulder", p1: "rightElbow", p2: "rightShoulder", p3: "rightHip" },
      goodRange: [60, 100], warningRange: [40, 60], criticalRange: [0, 40],
      side: "right", phase: "Setup", weight: 5,
      cueGood: "Shoulders neutral and retracted", cueWarning: "Shoulders rounding forward — pull them back", cueCritical: "Shoulders severely protracted — retract and stabilize",
    },
    {
      id: "rdl-hip-stability-single-l", name: "Hip Stability Single Leg (Left Stance)",
      description: "Stance hip stability during single-leg RDL. The hip should remain stable without hiking or dropping.",
      angle: { joint: "leftHip", p1: "rightHip", p2: "leftHip", p3: "leftKnee" },
      goodRange: [80, 100], warningRange: [65, 80], criticalRange: [0, 65],
      side: "left", phase: "Hinge", weight: 7,
      cueGood: "Hip stable throughout the movement", cueWarning: "Hip hiking or dropping — engage glute medius", cueCritical: "Significant hip instability — reduce range or use support",
    },
    {
      id: "rdl-hip-stability-single-r", name: "Hip Stability Single Leg (Right Stance)",
      description: "Stance hip stability during single-leg RDL for the right leg.",
      angle: { joint: "rightHip", p1: "leftHip", p2: "rightHip", p3: "rightKnee" },
      goodRange: [80, 100], warningRange: [65, 80], criticalRange: [0, 65],
      side: "right", phase: "Hinge", weight: 7,
      cueGood: "Hip stable throughout the movement", cueWarning: "Hip hiking or dropping — engage glute medius", cueCritical: "Significant hip instability — reduce range or use support",
    },
    {
      id: "rdl-nonworking-leg-lift-l", name: "Lifted Leg Extension (Left Stance)",
      description: "The non-stance leg trails straight behind as a counterbalance during single-leg RDL. Knee should be nearly straight.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [165, 180], warningRange: [145, 165], criticalRange: [0, 145],
      side: "right", phase: "Bottom", weight: 5,
      cueGood: "Lifted leg extended straight behind", cueWarning: "Lifted leg is bending — straighten it for balance", cueCritical: "Lifted leg too bent — kick back through the hip",
    },
    {
      id: "rdl-nonworking-leg-lift-r", name: "Lifted Leg Extension (Right Stance)",
      description: "The non-stance leg trails behind when the right leg is the stance leg.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [165, 180], warningRange: [145, 165], criticalRange: [0, 145],
      side: "left", phase: "Bottom", weight: 5,
      cueGood: "Lifted leg extended straight behind", cueWarning: "Lifted leg is bending — straighten it for balance", cueCritical: "Lifted leg too bent — kick back through the hip",
    },
  ],
  phases: [
    { name: "Setup", description: "Stand with feet hip-width apart (bilateral) or on one leg (single-leg), weight at hip level." },
    { name: "Hinge", description: "Push hips back while keeping the spine neutral and knees slightly bent. Torso lowers as hips translate backward." },
    { name: "Bottom", description: "Maximum hip flexion with torso near parallel. Posterior chain under full stretch. Single-leg: lifted leg trails behind." },
    { name: "Return", description: "Drive the hips forward to return upright by contracting the glutes and hamstrings." },
  ],
};

// ────────────────────────────────────────────────────────────
// 3. BULGARIAN SPLIT SQUAT
// ────────────────────────────────────────────────────────────
export const bulgarianSplitSquat: ExerciseBiomechanics = {
  id: "bulgarian-split-squat",
  name: "Bulgarian Split Squat",
  aliases: ["BSS", "Rear Foot Elevated Split Squat", "RFESS"],
  category: "legs",
  description: "Split squat with the rear foot elevated on a bench. Targets the quadriceps, glutes, and stabilizer muscles unilaterally.",
  tags: ["legs", "quads", "glutes", "unilateral", "stability", "split-stance"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex", "leftEar", "rightEar"],
  checkpoints: [
    {
      id: "bss-front-knee-angle-l", name: "Front Knee Angle (Left Front)",
      description: "Knee flexion of the front left leg at the bottom. Target: ~90° for optimal quad activation.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [75, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "left", phase: "Bottom", weight: 10,
      cueGood: "Front knee at optimal 90° depth", cueWarning: "Not deep enough — increase knee bend", cueCritical: "Very shallow — lower the hips further",
    },
    {
      id: "bss-front-knee-angle-r", name: "Front Knee Angle (Right Front)",
      description: "Knee flexion of the front right leg at the bottom.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [75, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "right", phase: "Bottom", weight: 10,
      cueGood: "Front knee at optimal 90° depth", cueWarning: "Not deep enough — increase knee bend", cueCritical: "Very shallow — lower the hips further",
    },
    {
      id: "bss-front-knee-tracking-l", name: "Front Knee Tracking (Left)",
      description: "Front knee alignment relative to the foot. The knee should track over the second toe without caving inward.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftFootIndex" },
      goodRange: [165, 180], warningRange: [155, 165], criticalRange: [0, 155],
      side: "left", phase: "Descent", weight: 9,
      cueGood: "Knee tracking properly over foot", cueWarning: "Knee drifting inward — push knee out", cueCritical: "Knee valgus collapse — drive knee outward",
    },
    {
      id: "bss-front-knee-tracking-r", name: "Front Knee Tracking (Right)",
      description: "Front knee alignment for the right leg.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightFootIndex" },
      goodRange: [165, 180], warningRange: [155, 165], criticalRange: [0, 155],
      side: "right", phase: "Descent", weight: 9,
      cueGood: "Knee tracking properly over foot", cueWarning: "Knee drifting inward — push knee out", cueCritical: "Knee valgus collapse — drive knee outward",
    },
    {
      id: "bss-ankle-dorsiflexion-l", name: "Front Ankle Dorsiflexion (Left)",
      description: "Ankle dorsiflexion of the front left leg. Adequate mobility allows the knee to track forward over the toes.",
      angle: { joint: "leftAnkle", p1: "leftKnee", p2: "leftAnkle", p3: "leftFootIndex" },
      goodRange: [80, 105], warningRange: [60, 80], criticalRange: [0, 60],
      side: "left", phase: "Bottom", weight: 6,
      cueGood: "Good ankle mobility in front leg", cueWarning: "Limited dorsiflexion — stretch ankle or elevate heel", cueCritical: "Very limited ankle mobility — heel likely lifting",
    },
    {
      id: "bss-ankle-dorsiflexion-r", name: "Front Ankle Dorsiflexion (Right)",
      description: "Ankle dorsiflexion of the front right leg.",
      angle: { joint: "rightAnkle", p1: "rightKnee", p2: "rightAnkle", p3: "rightFootIndex" },
      goodRange: [80, 105], warningRange: [60, 80], criticalRange: [0, 60],
      side: "right", phase: "Bottom", weight: 6,
      cueGood: "Good ankle mobility in front leg", cueWarning: "Limited dorsiflexion — stretch ankle or elevate heel", cueCritical: "Very limited ankle mobility — heel likely lifting",
    },
    {
      id: "bss-trunk-angle-l", name: "Trunk Angle (Left Front)",
      description: "Torso lean angle during the split squat. The trunk should remain upright to slightly leaned forward.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [60, 90], warningRange: [40, 60], criticalRange: [0, 40],
      side: "left", phase: "Bottom", weight: 7,
      cueGood: "Trunk upright with appropriate lean", cueWarning: "Torso leaning too far forward — keep chest tall", cueCritical: "Excessive forward lean — core engagement needed",
    },
    {
      id: "bss-trunk-angle-r", name: "Trunk Angle (Right Front)",
      description: "Torso lean angle for the right leg forward variation.",
      angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "rightKnee" },
      goodRange: [60, 90], warningRange: [40, 60], criticalRange: [0, 40],
      side: "right", phase: "Bottom", weight: 7,
      cueGood: "Trunk upright with appropriate lean", cueWarning: "Torso leaning too far forward — keep chest tall", cueCritical: "Excessive forward lean — core engagement needed",
    },
    {
      id: "bss-hip-angle-front-back-l", name: "Hip Angle Front-to-Back (Left Front)",
      description: "Angular relationship between the front and back legs. The back hip should be in a stable, slightly extended position on the bench.",
      angle: { joint: "leftHip", p1: "rightHip", p2: "leftHip", p3: "leftKnee" },
      goodRange: [70, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "left", phase: "Bottom", weight: 5,
      cueGood: "Good hip separation between front and back leg", cueWarning: "Hip position too closed — widen stance slightly", cueCritical: "Hip position compromised — adjust foot placement",
    },
    {
      id: "bss-hip-angle-front-back-r", name: "Hip Angle Front-to-Back (Right Front)",
      description: "Angular relationship for the right front leg variation.",
      angle: { joint: "rightHip", p1: "leftHip", p2: "rightHip", p3: "rightKnee" },
      goodRange: [70, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "right", phase: "Bottom", weight: 5,
      cueGood: "Good hip separation between front and back leg", cueWarning: "Hip position too closed — widen stance slightly", cueCritical: "Hip position compromised — adjust foot placement",
    },
    {
      id: "bss-hip-flexion-bottom-l", name: "Front Hip Flexion at Bottom (Left)",
      description: "Hip flexion of the front left leg at the bottom of the movement. Target: ~70-90°.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [65, 95], warningRange: [95, 120], criticalRange: [120, 180],
      side: "left", phase: "Bottom", weight: 7,
      cueGood: "Front hip at ideal flexion depth", cueWarning: "Increase hip flexion for deeper stretch", cueCritical: "Front hip not reaching depth — lower further",
    },
    {
      id: "bss-hip-flexion-bottom-r", name: "Front Hip Flexion at Bottom (Right)",
      description: "Hip flexion of the front right leg at the bottom.",
      angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "rightKnee" },
      goodRange: [65, 95], warningRange: [95, 120], criticalRange: [120, 180],
      side: "right", phase: "Bottom", weight: 7,
      cueGood: "Front hip at ideal flexion depth", cueWarning: "Increase hip flexion for deeper stretch", cueCritical: "Front hip not reaching depth — lower further",
    },
  ],
  phases: [
    { name: "Setup", description: "Place rear foot on a bench, front foot planted firmly, torso upright." },
    { name: "Descent", description: "Lower the hips by bending the front knee. The rear knee descends toward the ground." },
    { name: "Bottom", description: "Front thigh parallel to the ground, rear knee hovering just above the floor." },
    { name: "Ascent", description: "Drive through the front heel to extend the front knee and return to the starting position." },
  ],
};

// ────────────────────────────────────────────────────────────
// 4. ABDUCTORS (Outer Thigh - Machine / Cable)
// ────────────────────────────────────────────────────────────
export const abductorMachine: ExerciseBiomechanics = {
  id: "abductor-machine",
  name: "Abductor Machine",
  aliases: ["Hip Abduction Machine", "Outer Thigh Machine", "Cable Abduction"],
  category: "legs",
  description: "Seated or standing hip abduction targeting the glute medius and minimus. Performed on a machine or with cables.",
  tags: ["legs", "abductors", "glute-medius", "hips", "machine", "isolation"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle"],
  checkpoints: [
    {
      id: "abductor-hip-abduction-angle-l", name: "Hip Abduction Angle (Left)",
      description: "Angle of the left leg away from the midline during the open phase. Target: full range of motion without pelvic compensation.",
      angle: { joint: "leftHip", p1: "rightHip", p2: "leftHip", p3: "leftKnee" },
      goodRange: [30, 55], warningRange: [55, 70], criticalRange: [70, 180],
      side: "left", phase: "Peak", weight: 9,
      cueGood: "Good abduction range of motion", cueWarning: "Reduce range — avoid leaning to compensate", cueCritical: "Excessive pelvic tilt — engage core and reduce ROM",
    },
    {
      id: "abductor-hip-abduction-angle-r", name: "Hip Abduction Angle (Right)",
      description: "Angle of the right leg away from the midline.",
      angle: { joint: "rightHip", p1: "leftHip", p2: "rightHip", p3: "rightKnee" },
      goodRange: [30, 55], warningRange: [55, 70], criticalRange: [70, 180],
      side: "right", phase: "Peak", weight: 9,
      cueGood: "Good abduction range of motion", cueWarning: "Reduce range — avoid leaning to compensate", cueCritical: "Excessive pelvic tilt — engage core and reduce ROM",
    },
    {
      id: "abductor-trunk-stability", name: "Trunk Stability",
      description: "The trunk should remain stable throughout the movement. Leaning to either side compensates by reducing the effective load on the abductors.",
      angle: { joint: "leftShoulder", p1: "leftEar", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "both", phase: "Open", weight: 7,
      cueGood: "Trunk stable and upright", cueWarning: "Trunk leaning — reduce weight and stabilize through the core", cueCritical: "Significant trunk compensation — use lighter weight",
    },
    {
      id: "abductor-knee-position-l", name: "Knee Position (Left)",
      description: "Knee should remain in a neutral position (not rotated) throughout the abduction. Internal or external rotation reduces isolation effectiveness.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [160, 180], warningRange: [140, 160], criticalRange: [0, 140],
      side: "left", phase: "Open", weight: 5,
      cueGood: "Knee neutral — proper alignment", cueWarning: "Knee rotating — keep foot and knee aligned", cueCritical: "Knee severely rotated — reset and focus on knee position",
    },
    {
      id: "abductor-knee-position-r", name: "Knee Position (Right)",
      description: "Knee position for the right leg during abduction.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [160, 180], warningRange: [140, 160], criticalRange: [0, 140],
      side: "right", phase: "Open", weight: 5,
      cueGood: "Knee neutral — proper alignment", cueWarning: "Knee rotating — keep foot and knee aligned", cueCritical: "Knee severely rotated — reset and focus on knee position",
    },
    {
      id: "abductor-rom-symmetry", name: "Range of Motion Symmetry",
      description: "Comparison of left and right abduction ROM. Significant asymmetry may indicate unilateral weakness or mobility restriction.",
      angle: { joint: "leftHip", p1: "rightHip", p2: "leftHip", p3: "leftKnee" },
      goodRange: [28, 55], warningRange: [20, 28], criticalRange: [0, 20],
      side: "both", phase: "Peak", weight: 6,
      cueGood: "ROM consistent between sides", cueWarning: "ROM asymmetry detected — investigate unilateral limitation", cueCritical: "Significant ROM asymmetry — address mobility or strength imbalance",
    },
  ],
  phases: [
    { name: "Start", description: "Legs together at the midline with the pads against the outer thighs." },
    { name: "Open", description: "Push the legs apart against resistance by abducting at the hips." },
    { name: "Peak", description: "Maximum abduction with a brief isometric hold. Feel the glute medius contract." },
    { name: "Return", description: "Control the legs back to the starting position without letting the weight stack drop." },
  ],
};

// ────────────────────────────────────────────────────────────
// 5. ADDUCTORS / SUMO SQUAT (Inner Thigh)
// ────────────────────────────────────────────────────────────
export const sumoSquatAdductor: ExerciseBiomechanics = {
  id: "sumo-squat-adductor",
  name: "Sumo Squat",
  aliases: ["Sumo Squat", "Adductor Squat", "Wide Stance Squat", "Plie Squat"],
  category: "legs",
  description: "Wide-stance squat emphasizing the adductors (inner thighs) along with the glutes and quads. Feet turned outward.",
  tags: ["legs", "adductors", "inner-thigh", "quads", "glutes", "wide-stance"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex"],
  checkpoints: [
    {
      id: "sumo-knee-angle-l", name: "Knee Angle (Left)",
      description: "Knee flexion of the left leg at the bottom of the sumo squat. Target: ~90° for full depth.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [70, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "left", phase: "Bottom", weight: 9,
      cueGood: "Good depth at bottom position", cueWarning: "Not deep enough — increase knee bend", cueCritical: "Very shallow squat — lower hips further",
    },
    {
      id: "sumo-knee-angle-r", name: "Knee Angle (Right)",
      description: "Knee flexion of the right leg at the bottom of the sumo squat.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [70, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "right", phase: "Bottom", weight: 9,
      cueGood: "Good depth at bottom position", cueWarning: "Not deep enough — increase knee bend", cueCritical: "Very shallow squat — lower hips further",
    },
    {
      id: "sumo-knee-tracking-l", name: "Knee Tracking (Left)",
      description: "Knee alignment over the foot in the wide stance. The knee should track in line with the foot despite the externally rotated position.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftFootIndex" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "left", phase: "Descent", weight: 9,
      cueGood: "Knee tracking in line with the foot", cueWarning: "Knee collapsing inward — push knees out toward toes", cueCritical: "Knee valgus — actively push knees apart",
    },
    {
      id: "sumo-knee-tracking-r", name: "Knee Tracking (Right)",
      description: "Knee alignment for the right leg in the wide stance.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightFootIndex" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "right", phase: "Descent", weight: 9,
      cueGood: "Knee tracking in line with the foot", cueWarning: "Knee collapsing inward — push knees out toward toes", cueCritical: "Knee valgus — actively push knees apart",
    },
    {
      id: "sumo-hip-angle-l", name: "Hip Angle Wide Stance (Left)",
      description: "Hip angle in the wide stance position. The wide stance creates a larger hip angle compared to conventional squats, targeting the adductors.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [40, 70], warningRange: [70, 90], criticalRange: [90, 180],
      side: "left", phase: "Bottom", weight: 7,
      cueGood: "Hip angle appropriate for sumo stance", cueWarning: "Hip angle too open — may not be in full sumo stance", cueCritical: "Hip angle too closed — consider wider foot placement",
    },
    {
      id: "sumo-hip-angle-r", name: "Hip Angle Wide Stance (Right)",
      description: "Hip angle for the right leg in the sumo stance.",
      angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "rightKnee" },
      goodRange: [40, 70], warningRange: [70, 90], criticalRange: [90, 180],
      side: "right", phase: "Bottom", weight: 7,
      cueGood: "Hip angle appropriate for sumo stance", cueWarning: "Hip angle too open — may not be in full sumo stance", cueCritical: "Hip angle too closed — consider wider foot placement",
    },
    {
      id: "sumo-trunk-lean", name: "Trunk Lean (Upright)",
      description: "The trunk should remain relatively upright in the sumo squat compared to a conventional squat. Excessive forward lean reduces adductor engagement.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [40, 65], warningRange: [65, 85], criticalRange: [85, 180],
      side: "both", phase: "Bottom", weight: 6,
      cueGood: "Trunk upright — good sumo form", cueWarning: "Trunk leaning too far forward — keep chest up", cueCritical: "Excessive forward lean — stand taller through the torso",
    },
    {
      id: "sumo-ankle-stability-l", name: "Ankle Stability (Left)",
      description: "Ankle stability in the wide stance. The ankle should remain stable with even weight distribution across the foot.",
      angle: { joint: "leftAnkle", p1: "leftKnee", p2: "leftAnkle", p3: "leftFootIndex" },
      goodRange: [75, 95], warningRange: [60, 75], criticalRange: [0, 60],
      side: "left", phase: "Bottom", weight: 5,
      cueGood: "Ankle stable and balanced", cueWarning: "Ankle instability — check foot pressure distribution", cueCritical: "Ankle collapsing — engage the arch and distribute weight evenly",
    },
    {
      id: "sumo-ankle-stability-r", name: "Ankle Stability (Right)",
      description: "Ankle stability for the right leg in the sumo stance.",
      angle: { joint: "rightAnkle", p1: "rightKnee", p2: "rightAnkle", p3: "rightFootIndex" },
      goodRange: [75, 95], warningRange: [60, 75], criticalRange: [0, 60],
      side: "right", phase: "Bottom", weight: 5,
      cueGood: "Ankle stable and balanced", cueWarning: "Ankle instability — check foot pressure distribution", cueCritical: "Ankle collapsing — engage the arch",
    },
  ],
  phases: [
    { name: "Setup", description: "Feet wider than shoulder-width with toes turned outward. Hips in neutral position." },
    { name: "Descent", description: "Push hips back and bend knees, keeping the torso upright and knees tracking over the toes." },
    { name: "Bottom", description: "Thighs parallel or slightly below parallel. Knees should be stable and tracking outward." },
    { name: "Ascent", description: "Drive through the whole foot, extending the hips and knees to return upright." },
  ],
};

// ────────────────────────────────────────────────────────────
// 6. HIP THRUSTS
// ────────────────────────────────────────────────────────────
export const hipThrust: ExerciseBiomechanics = {
  id: "hip-thrust",
  name: "Hip Thrust",
  aliases: ["Glute Bridge", "Barbell Hip Thrust", "Booty Thrust"],
  category: "legs",
  description: "Hip extension exercise performed with the upper back on a bench. Primary glute builder emphasizing full hip extension.",
  tags: ["legs", "glutes", "hip-extension", "posterior-chain", "bench"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftHeel", "rightHeel", "leftEar", "rightEar", "leftElbow", "rightElbow"],
  checkpoints: [
    {
      id: "hipthrust-hip-angle-peak", name: "Hip Angle at Peak",
      description: "Hip angle at the top of the thrust. Full hip extension should be achieved with the torso and thighs forming a straight line.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [170, 190], warningRange: [155, 170], criticalRange: [0, 155],
      side: "both", phase: "Peak", weight: 10,
      cueGood: "Full hip extension at the top", cueWarning: "Not fully extending — squeeze glutes to drive hips higher", cueCritical: "Hip barely extended — push through the heels and lift hips",
    },
    {
      id: "hipthrust-hip-angle-bottom", name: "Hip Angle at Bottom",
      description: "Hip angle at the bottom position. Hips should descend to approximately 90° before driving back up.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [80, 105], warningRange: [60, 80], criticalRange: [0, 60],
      side: "both", phase: "Lift", weight: 6,
      cueGood: "Good range from bottom to top", cueWarning: "Not lowering enough — increase ROM for better glute activation", cueCritical: "Very shallow range — lower hips further",
    },
    {
      id: "hipthrust-spine-neutrality", name: "Spine Neutrality",
      description: "The spine should remain neutral at the top of the thrust. Overextension of the lower back indicates excessive arching.",
      angle: { joint: "leftShoulder", p1: "leftEar", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [155, 180], warningRange: [140, 155], criticalRange: [0, 140],
      side: "both", phase: "Peak", weight: 9,
      cueGood: "Spine neutral at the top", cueWarning: "Slight over-extension — tuck ribs down", cueCritical: "Excessive back arching — reduce range and engage core",
    },
    {
      id: "hipthrust-ribcage-position", name: "Ribcage Position",
      description: "The ribcage should remain down (depressed) throughout. Flaring ribs indicates overextension of the thoracic spine.",
      angle: { joint: "leftShoulder", p1: "nose", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [155, 180], warningRange: [140, 155], criticalRange: [0, 140],
      side: "both", phase: "Peak", weight: 7,
      cueGood: "Ribs down — core engaged", cueWarning: "Ribs beginning to flare — brace core and pull ribs down", cueCritical: "Ribs flared — posterior pelvic tilt and brace",
    },
    {
      id: "hipthrust-knee-angle-l", name: "Knee Angle (Left)",
      description: "Knee angle should remain fixed at approximately 90° throughout the hip thrust. Changing knee angle indicates compensatory movement.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [75, 100], warningRange: [60, 75], criticalRange: [0, 60],
      side: "left", phase: "Lift", weight: 7,
      cueGood: "Knee angle stable at ~90°", cueWarning: "Knee angle changing — keep shins vertical", cueCritical: "Knee moving excessively — fix foot position",
    },
    {
      id: "hipthrust-knee-angle-r", name: "Knee Angle (Right)",
      description: "Knee angle for the right leg during hip thrusts.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [75, 100], warningRange: [60, 75], criticalRange: [0, 60],
      side: "right", phase: "Lift", weight: 7,
      cueGood: "Knee angle stable at ~90°", cueWarning: "Knee angle changing — keep shins vertical", cueCritical: "Knee moving excessively — fix foot position",
    },
    {
      id: "hipthrust-shoulder-position-l", name: "Shoulder Position on Bench (Left)",
      description: "Shoulder blades should be positioned on the bench edge. The angle between the arm, shoulder, and torso indicates proper placement.",
      angle: { joint: "leftShoulder", p1: "leftElbow", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [70, 110], warningRange: [50, 70], criticalRange: [0, 50],
      side: "left", phase: "Setup", weight: 5,
      cueGood: "Shoulders properly positioned on bench", cueWarning: "Shoulder position shifting — adjust bench distance", cueCritical: "Shoulders not on bench — reposition before lifting",
    },
    {
      id: "hipthrust-shoulder-position-r", name: "Shoulder Position on Bench (Right)",
      description: "Shoulder position for the right side on the bench.",
      angle: { joint: "rightShoulder", p1: "rightElbow", p2: "rightShoulder", p3: "rightHip" },
      goodRange: [70, 110], warningRange: [50, 70], criticalRange: [0, 50],
      side: "right", phase: "Setup", weight: 5,
      cueGood: "Shoulders properly positioned on bench", cueWarning: "Shoulder position shifting — adjust bench distance", cueCritical: "Shoulders not on bench — reposition",
    },
  ],
  phases: [
    { name: "Setup", description: "Upper back resting on the bench, feet flat on the ground hip-width apart, barbell over the hips." },
    { name: "Lift", description: "Drive through the heels to lift the hips toward the ceiling. Squeeze the glutes at the top." },
    { name: "Peak", description: "Full hip extension with a brief isometric hold. Knees at 90°, shins vertical, shoulders on bench." },
    { name: "Lower", description: "Control the hips back down to the starting position without letting them drop." },
  ],
};

// ────────────────────────────────────────────────────────────
// 7. LEG EXTENSIONS (Machine)
// ────────────────────────────────────────────────────────────
export const legExtension: ExerciseBiomechanics = {
  id: "leg-extension",
  name: "Leg Extension",
  aliases: ["Leg Extension Machine", "Knee Extension"],
  category: "legs",
  description: "Isolated knee extension on a machine targeting the quadriceps. Performed seated with the pad against the shins.",
  tags: ["legs", "quads", "knee-extension", "machine", "isolation"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex"],
  checkpoints: [
    {
      id: "legext-knee-angle-start-l", name: "Knee Angle at Start (Left)",
      description: "Knee angle at the start position with the machine pads against the shins. The knee should be at ~90°.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [75, 100], warningRange: [60, 75], criticalRange: [0, 60],
      side: "left", phase: "Start", weight: 6,
      cueGood: "Starting knee angle at 90°", cueWarning: "Adjust the seat — knee angle too closed", cueCritical: "Seat position wrong — adjust machine setup",
    },
    {
      id: "legext-knee-angle-start-r", name: "Knee Angle at Start (Right)",
      description: "Knee angle at the start position for the right leg.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [75, 100], warningRange: [60, 75], criticalRange: [0, 60],
      side: "right", phase: "Start", weight: 6,
      cueGood: "Starting knee angle at 90°", cueWarning: "Adjust the seat — knee angle too closed", cueCritical: "Seat position wrong — adjust machine setup",
    },
    {
      id: "legext-knee-angle-peak-l", name: "Knee Angle at Peak (Left)",
      description: "Knee angle at full extension. The knee should reach near-full extension (170-180°) at the peak of the movement.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "left", phase: "Peak", weight: 9,
      cueGood: "Full knee extension achieved", cueWarning: "Not fully extending — push through full range", cueCritical: "Very limited extension — reduce weight and focus on full ROM",
    },
    {
      id: "legext-knee-angle-peak-r", name: "Knee Angle at Peak (Right)",
      description: "Knee angle at full extension for the right leg.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "right", phase: "Peak", weight: 9,
      cueGood: "Full knee extension achieved", cueWarning: "Not fully extending — push through full range", cueCritical: "Very limited extension — reduce weight and focus on full ROM",
    },
    {
      id: "legext-hip-angle", name: "Hip Angle (Seated)",
      description: "Hip angle while seated on the machine. The hip should remain fixed at approximately 90° throughout the movement.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [75, 105], warningRange: [60, 75], criticalRange: [0, 60],
      side: "both", phase: "Extend", weight: 5,
      cueGood: "Hip angle stable in the seat", cueWarning: "Hip angle shifting — sit back and stabilize", cueCritical: "Hip position compromised — adjust seat back",
    },
    {
      id: "legext-ankle-position-l", name: "Ankle Position (Left)",
      description: "Ankle should remain in a neutral position throughout the extension. Pointing the toe (plantarflexion) is a cheating strategy that reduces quad load.",
      angle: { joint: "leftAnkle", p1: "leftKnee", p2: "leftAnkle", p3: "leftFootIndex" },
      goodRange: [75, 100], warningRange: [60, 75], criticalRange: [0, 60],
      side: "left", phase: "Extend", weight: 4,
      cueGood: "Ankle neutral", cueWarning: "Ankle pointing — keep foot neutral", cueCritical: "Ankle severely pointing — dorsiflex to maintain quad tension",
    },
    {
      id: "legext-ankle-position-r", name: "Ankle Position (Right)",
      description: "Ankle position for the right leg during extension.",
      angle: { joint: "rightAnkle", p1: "rightKnee", p2: "rightAnkle", p3: "rightFootIndex" },
      goodRange: [75, 100], warningRange: [60, 75], criticalRange: [0, 60],
      side: "right", phase: "Extend", weight: 4,
      cueGood: "Ankle neutral", cueWarning: "Ankle pointing — keep foot neutral", cueCritical: "Ankle severely pointing — dorsiflex to maintain quad tension",
    },
    {
      id: "legext-trunk-position", name: "Trunk Position",
      description: "The trunk should remain upright against the back pad. Leaning forward or backward shifts load and reduces isolation effectiveness.",
      angle: { joint: "leftShoulder", p1: "leftEar", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [155, 180], warningRange: [135, 155], criticalRange: [0, 135],
      side: "both", phase: "Extend", weight: 5,
      cueGood: "Trunk upright and stable", cueWarning: "Trunk leaning — sit back against the pad", cueCritical: "Trunk position compromised — reset posture",
    },
  ],
  phases: [
    { name: "Start", description: "Seated with the machine pad across the shins just above the ankles. Knees at ~90°." },
    { name: "Extend", description: "Extend the knees by contracting the quadriceps in a controlled motion." },
    { name: "Peak", description: "Full knee extension with a brief squeeze of the quads at the top." },
    { name: "Lower", description: "Slowly lower the weight back to the starting position without letting it drop." },
  ],
};

// ────────────────────────────────────────────────────────────
// 8. CABLE KICKBACKS (45° Leg + Sideways)
// ────────────────────────────────────────────────────────────
export const cableKickback: ExerciseBiomechanics = {
  id: "cable-kickback",
  name: "Cable Kickback",
  aliases: ["Cable Hip Extension", "Glute Kickback", "45° Leg Kickback", "Side Cable Abduction"],
  category: "legs",
  description: "Cable-based hip extension targeting the glutes. Can be performed with a 45° forward lean or sideways for hip abduction emphasis.",
  tags: ["legs", "glutes", "hip-extension", "cable", "unilateral", "hip-abduction"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex", "leftEar", "rightEar"],
  checkpoints: [
    {
      id: "kickback-hip-extension-l", name: "Hip Extension Angle (Left)",
      description: "Angle of the left leg extending behind the body during a kickback. The hip should achieve full extension with the leg behind the torso.",
      angle: { joint: "leftHip", p1: "leftKnee", p2: "leftHip", p3: "leftShoulder" },
      goodRange: [140, 175], warningRange: [120, 140], criticalRange: [0, 120],
      side: "left", phase: "Peak", weight: 9,
      cueGood: "Full hip extension achieved", cueWarning: "Extend the leg further back — squeeze glute", cueCritical: "Minimal hip extension — kick back through the hip",
    },
    {
      id: "kickback-hip-extension-r", name: "Hip Extension Angle (Right)",
      description: "Angle of the right leg extending behind the body.",
      angle: { joint: "rightHip", p1: "rightKnee", p2: "rightHip", p3: "rightShoulder" },
      goodRange: [140, 175], warningRange: [120, 140], criticalRange: [0, 120],
      side: "right", phase: "Peak", weight: 9,
      cueGood: "Full hip extension achieved", cueWarning: "Extend the leg further back — squeeze glute", cueCritical: "Minimal hip extension — kick back through the hip",
    },
    {
      id: "kickback-knee-angle-l", name: "Knee Angle (Left)",
      description: "The knee should maintain a slight bend (~10°) throughout the kickback. Locking out or over-bending shifts load from the glutes.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [160, 175], warningRange: [145, 160], criticalRange: [0, 145],
      side: "left", phase: "Kick", weight: 6,
      cueGood: "Knee slightly bent — optimal", cueWarning: "Knee too straight — maintain slight bend", cueCritical: "Knee over-bent — leg should be nearly straight",
    },
    {
      id: "kickback-knee-angle-r", name: "Knee Angle (Right)",
      description: "Knee angle for the right leg during kickback.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [160, 175], warningRange: [145, 160], criticalRange: [0, 145],
      side: "right", phase: "Kick", weight: 6,
      cueGood: "Knee slightly bent — optimal", cueWarning: "Knee too straight — maintain slight bend", cueCritical: "Knee over-bent — leg should be nearly straight",
    },
    {
      id: "kickback-trunk-lean-l", name: "Trunk Lean (Left Working)",
      description: "For 45° kickbacks: the trunk should lean forward at approximately 45°. Too upright or too horizontal reduces glute isolation.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [110, 145], warningRange: [90, 110], criticalRange: [0, 90],
      side: "left", phase: "Kick", weight: 6,
      cueGood: "Trunk at appropriate forward lean", cueWarning: "Trunk too upright — hinge forward more", cueCritical: "Trunk too horizontal — reduce forward lean",
    },
    {
      id: "kickback-trunk-lean-r", name: "Trunk Lean (Right Working)",
      description: "Trunk lean for the right leg kickback.",
      angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "rightKnee" },
      goodRange: [110, 145], warningRange: [90, 110], criticalRange: [0, 90],
      side: "right", phase: "Kick", weight: 6,
      cueGood: "Trunk at appropriate forward lean", cueWarning: "Trunk too upright — hinge forward more", cueCritical: "Trunk too horizontal — reduce forward lean",
    },
    {
      id: "kickback-pelvis-stability-l", name: "Pelvis Stability (Left Working)",
      description: "The pelvis should remain stable and square during the kickback. Pelvic rotation or hiking indicates compensation.",
      angle: { joint: "leftHip", p1: "rightHip", p2: "leftHip", p3: "leftKnee" },
      goodRange: [80, 100], warningRange: [65, 80], criticalRange: [0, 65],
      side: "left", phase: "Kick", weight: 7,
      cueGood: "Pelvis stable — no rotation", cueWarning: "Pelvis hiking or rotating — reduce ROM and engage core", cueCritical: "Significant pelvic instability — lower weight and focus on form",
    },
    {
      id: "kickback-pelvis-stability-r", name: "Pelvis Stability (Right Working)",
      description: "Pelvis stability for the right leg kickback.",
      angle: { joint: "rightHip", p1: "leftHip", p2: "rightHip", p3: "rightKnee" },
      goodRange: [80, 100], warningRange: [65, 80], criticalRange: [0, 65],
      side: "right", phase: "Kick", weight: 7,
      cueGood: "Pelvis stable — no rotation", cueWarning: "Pelvis hiking or rotating — reduce ROM and engage core", cueCritical: "Significant pelvic instability — lower weight",
    },
    {
      id: "kickback-side-abduction-l", name: "Sideways Hip Abduction (Left)",
      description: "For sideways kickbacks: the leg abducts laterally away from the midline. Target: controlled abduction without torso lean.",
      angle: { joint: "leftHip", p1: "rightHip", p2: "leftHip", p3: "leftKnee" },
      goodRange: [20, 45], warningRange: [10, 20], criticalRange: [0, 10],
      side: "left", phase: "Peak", weight: 5,
      cueGood: "Good lateral abduction range", cueWarning: "Limited range — focus on glute medius contraction", cueCritical: "Minimal abduction — check cable position and ROM",
    },
    {
      id: "kickback-side-abduction-r", name: "Sideways Hip Abduction (Right)",
      description: "Sideways hip abduction for the right leg.",
      angle: { joint: "rightHip", p1: "leftHip", p2: "rightHip", p3: "rightKnee" },
      goodRange: [20, 45], warningRange: [10, 20], criticalRange: [0, 10],
      side: "right", phase: "Peak", weight: 5,
      cueGood: "Good lateral abduction range", cueWarning: "Limited range — focus on glute medius contraction", cueCritical: "Minimal abduction — check cable position",
    },
  ],
  phases: [
    { name: "Start", description: "Stand facing the cable machine (45° version) or sideways, cable attached to the working ankle." },
    { name: "Kick", description: "Extend the working leg back (45°) or out to the side (sideways) against cable resistance." },
    { name: "Peak", description: "Maximum hip extension or abduction with a glute squeeze. Maintain pelvic stability." },
    { name: "Return", description: "Control the leg back to the starting position without letting the weight stack drop." },
  ],
};

// ────────────────────────────────────────────────────────────
// 9. SEATED/LYING HAMSTRING CURLS
// ────────────────────────────────────────────────────────────
export const hamstringCurl: ExerciseBiomechanics = {
  id: "hamstring-curl",
  name: "Hamstring Curl",
  aliases: ["Leg Curl", "Seated Hamstring Curl", "Lying Hamstring Curl", "Nordic Curl"],
  category: "legs",
  description: "Isolated knee flexion targeting the hamstrings. Performed seated or lying on a machine, or with a stability ball.",
  tags: ["legs", "hamstrings", "knee-flexion", "machine", "isolation"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex"],
  checkpoints: [
    {
      id: "hamcurl-knee-start-l", name: "Knee Angle at Start (Left)",
      description: "Knee angle at the start position. The leg should be fully extended (~180°) with the pad behind the ankle.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "left", phase: "Start", weight: 6,
      cueGood: "Fully extended starting position", cueWarning: "Knee not fully extended — straighten the leg", cueCritical: "Starting position too bent — adjust the machine",
    },
    {
      id: "hamcurl-knee-start-r", name: "Knee Angle at Start (Right)",
      description: "Knee angle at the start position for the right leg.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "right", phase: "Start", weight: 6,
      cueGood: "Fully extended starting position", cueWarning: "Knee not fully extended — straighten the leg", cueCritical: "Starting position too bent — adjust the machine",
    },
    {
      id: "hamcurl-knee-peak-l", name: "Knee Angle at Peak (Left)",
      description: "Knee angle at the peak of the curl. The knee should flex to approximately 90° (or more) to achieve full hamstring shortening.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [70, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "left", phase: "Peak", weight: 9,
      cueGood: "Full flexion achieved at peak", cueWarning: "Not curling enough — pull the heel toward the glute", cueCritical: "Very limited flexion — reduce weight and increase ROM",
    },
    {
      id: "hamcurl-knee-peak-r", name: "Knee Angle at Peak (Right)",
      description: "Knee angle at the peak of the curl for the right leg.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [70, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "right", phase: "Peak", weight: 9,
      cueGood: "Full flexion achieved at peak", cueWarning: "Not curling enough — pull the heel toward the glute", cueCritical: "Very limited flexion — reduce weight and increase ROM",
    },
    {
      id: "hamcurl-hip-position", name: "Hip Position",
      description: "The hip should remain fixed and stable throughout the curl. Lifting the hips off the pad (lying) or sliding forward (seated) reduces isolation.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "both", phase: "Curl", weight: 6,
      cueGood: "Hip stable and fixed", cueWarning: "Hip moving — stabilize against the pad", cueCritical: "Hip position compromised — reset and engage core",
    },
    {
      id: "hamcurl-ankle-position-l", name: "Ankle Position (Left)",
      description: "The ankle should remain neutral (dorsiflexed) throughout the curl. Pointing the toe reduces hamstring activation and allows cheating through the calf.",
      angle: { joint: "leftAnkle", p1: "leftKnee", p2: "leftAnkle", p3: "leftFootIndex" },
      goodRange: [75, 100], warningRange: [60, 75], criticalRange: [0, 60],
      side: "left", phase: "Curl", weight: 4,
      cueGood: "Ankle neutral — proper hamstring focus", cueWarning: "Ankle pointing — dorsiflex the foot", cueCritical: "Ankle severely plantarflexed — keep toe pulled toward shin",
    },
    {
      id: "hamcurl-ankle-position-r", name: "Ankle Position (Right)",
      description: "Ankle position for the right leg during the curl.",
      angle: { joint: "rightAnkle", p1: "rightKnee", p2: "rightAnkle", p3: "rightFootIndex" },
      goodRange: [75, 100], warningRange: [60, 75], criticalRange: [0, 60],
      side: "right", phase: "Curl", weight: 4,
      cueGood: "Ankle neutral — proper hamstring focus", cueWarning: "Ankle pointing — dorsiflex the foot", cueCritical: "Ankle severely plantarflexed — keep toe pulled toward shin",
    },
  ],
  phases: [
    { name: "Start", description: "Legs fully extended with the pad against the back of the ankles (lying) or front of the shins (seated)." },
    { name: "Curl", description: "Flex the knees to pull the pad toward the glutes by contracting the hamstrings." },
    { name: "Peak", description: "Maximum knee flexion with a brief hold. Squeeze the hamstrings at the peak." },
    { name: "Return", description: "Extend the knees slowly to return to the starting position without letting the weight drop." },
  ],
};

// ────────────────────────────────────────────────────────────
// 10. WALL SITS
// ────────────────────────────────────────────────────────────
export const wallSit: ExerciseBiomechanics = {
  id: "wall-sit",
  name: "Wall Sit",
  aliases: ["Wall Squat", "Wall Hold"],
  category: "legs",
  description: "Isometric squat held against a wall. Builds endurance in the quads, glutes, and core stabilizers.",
  tags: ["legs", "quads", "isometric", "endurance", "bodyweight", "glutes"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex", "leftEar", "rightEar"],
  checkpoints: [
    {
      id: "wallsit-knee-angle", name: "Knee Angle",
      description: "Knee angle during the wall sit. The target is 90° for standard wall sits. Deeper or shallower angles change the muscle emphasis.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [80, 100], warningRange: [100, 115], criticalRange: [115, 180],
      side: "both", phase: "Hold", weight: 9,
      cueGood: "Knee at 90° — optimal position", cueWarning: "Knee angle too open — slide feet farther from wall", cueCritical: "Knee angle too closed — slide feet closer to wall",
    },
    {
      id: "wallsit-hip-angle", name: "Hip Angle",
      description: "Hip angle during the wall sit. The hips should be at approximately 90°, creating a right angle between the torso and thighs.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [75, 100], warningRange: [100, 115], criticalRange: [115, 180],
      side: "both", phase: "Hold", weight: 8,
      cueGood: "Hips at 90° — good position", cueWarning: "Hips too high — slide down the wall", cueCritical: "Hips too low — raise to 90° for proper form",
    },
    {
      id: "wallsit-trunk-angle", name: "Trunk Angle (Wall Contact)",
      description: "The trunk should be flat against the wall. Excessive arching or leaning forward reduces wall support and shifts load.",
      angle: { joint: "leftShoulder", p1: "leftEar", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [160, 180], warningRange: [145, 160], criticalRange: [0, 145],
      side: "both", phase: "Hold", weight: 7,
      cueGood: "Back flat against the wall", cueWarning: "Lower back arching — press the spine into the wall", cueCritical: "Significant gap between back and wall — flatten the spine",
    },
    {
      id: "wallsit-foot-position", name: "Foot Position",
      description: "Feet should be shoulder-width apart and approximately 60cm from the wall. The angle of the shin relative to the ground indicates proper distance.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [80, 100], warningRange: [100, 115], criticalRange: [115, 180],
      side: "both", phase: "Setup", weight: 5,
      cueGood: "Foot position good — knees at 90°", cueWarning: "Feet too close — slide them farther from the wall", cueCritical: "Feet too far — slide them closer to the wall",
    },
    {
      id: "wallsit-spine-neutrality", name: "Spine Neutrality",
      description: "The spine should remain neutral with the lower back pressed into the wall. Avoid excessive posterior pelvic tilt.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [75, 100], warningRange: [100, 120], criticalRange: [120, 180],
      side: "both", phase: "Hold", weight: 6,
      cueGood: "Spine neutral against the wall", cueWarning: "Pelvis tilting — engage core to maintain neutral spine", cueCritical: "Spine position compromised — reset against the wall",
    },
  ],
  phases: [
    { name: "Setup", description: "Stand with back against the wall, feet shoulder-width apart, ~60cm from the wall." },
    { name: "Hold", description: "Slide down the wall until the knees and hips are at 90°. Hold the position isometrically." },
    { name: "Release", description: "Push through the feet to slide back up the wall to the standing position." },
  ],
};

// ────────────────────────────────────────────────────────────
// 11. SINGLE LEG RDL
// ────────────────────────────────────────────────────────────
export const singleLegRDL: ExerciseBiomechanics = {
  id: "single-leg-rdl",
  name: "Single Leg Romanian Deadlift",
  aliases: ["SL RDL", "Single Leg RDL", "Single Leg Hip Hinge"],
  category: "legs",
  description: "Unilateral hip-hinge on one leg with the opposite leg trailing behind as a counterbalance. Targets the hamstrings, glutes, and balance.",
  tags: ["legs", "hamstrings", "glutes", "balance", "unilateral", "hip-hinge", "posterior-chain"],
  landmarks: ["leftShoulder", "rightShoulder", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle", "leftFootIndex", "rightFootIndex", "leftEar", "rightEar"],
  checkpoints: [
    {
      id: "slrdl-hip-hinge-l", name: "Hip Hinge (Left Stance)",
      description: "Hip hinge depth on the left stance leg. The torso should descend to near parallel with the ground.",
      angle: { joint: "leftHip", p1: "leftShoulder", p2: "leftHip", p3: "leftKnee" },
      goodRange: [70, 100], warningRange: [100, 130], criticalRange: [130, 180],
      side: "left", phase: "Bottom", weight: 10,
      cueGood: "Good hinge depth on stance leg", cueWarning: "Not hinging deep enough — push hips back further", cueCritical: "Very shallow hinge — hinge from the hips, not the back",
    },
    {
      id: "slrdl-hip-hinge-r", name: "Hip Hinge (Right Stance)",
      description: "Hip hinge depth on the right stance leg.",
      angle: { joint: "rightHip", p1: "rightShoulder", p2: "rightHip", p3: "rightKnee" },
      goodRange: [70, 100], warningRange: [100, 130], criticalRange: [130, 180],
      side: "right", phase: "Bottom", weight: 10,
      cueGood: "Good hinge depth on stance leg", cueWarning: "Not hinging deep enough — push hips back further", cueCritical: "Very shallow hinge — hinge from the hips",
    },
    {
      id: "slrdl-spine-neutrality", name: "Spine Neutrality",
      description: "The spine must remain neutral throughout. Rounding the back is a primary injury risk in single-leg RDLs.",
      angle: { joint: "leftShoulder", p1: "leftEar", p2: "leftShoulder", p3: "leftHip" },
      goodRange: [155, 180], warningRange: [135, 155], criticalRange: [0, 135],
      side: "both", phase: "Hinge", weight: 10,
      cueGood: "Neutral spine maintained", cueWarning: "Spine beginning to round — chest up, shoulders back", cueCritical: "Spine severely rounded — stop and reset",
    },
    {
      id: "slrdl-knee-angle-stance-l", name: "Stance Knee Angle (Left)",
      description: "The stance leg knee should maintain a slight bend (~10-20°). A locked or over-bent knee shifts load and reduces hamstring focus.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [160, 175], warningRange: [175, 180], criticalRange: [0, 160],
      side: "left", phase: "Hinge", weight: 7,
      cueGood: "Stance knee slightly bent — optimal", cueWarning: "Stance knee too straight — unlock slightly", cueCritical: "Stance knee over-bent — keep the shin vertical",
    },
    {
      id: "slrdl-knee-angle-stance-r", name: "Stance Knee Angle (Right)",
      description: "Stance knee angle for the right leg.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [160, 175], warningRange: [175, 180], criticalRange: [0, 160],
      side: "right", phase: "Hinge", weight: 7,
      cueGood: "Stance knee slightly bent — optimal", cueWarning: "Stance knee too straight — unlock slightly", cueCritical: "Stance knee over-bent — keep the shin vertical",
    },
    {
      id: "slrdl-lifted-leg-l", name: "Lifted Leg Extension (Left Stance)",
      description: "The non-stance leg should trail straight behind as a counterbalance, with minimal knee bend.",
      angle: { joint: "rightKnee", p1: "rightHip", p2: "rightKnee", p3: "rightAnkle" },
      goodRange: [165, 180], warningRange: [145, 165], criticalRange: [0, 145],
      side: "right", phase: "Bottom", weight: 5,
      cueGood: "Lifted leg extended straight behind", cueWarning: "Lifted leg bending — straighten for balance", cueCritical: "Lifted leg too bent — extend through the hip",
    },
    {
      id: "slrdl-lifted-leg-r", name: "Lifted Leg Extension (Right Stance)",
      description: "The non-stance leg trailing behind when the right leg is the stance leg.",
      angle: { joint: "leftKnee", p1: "leftHip", p2: "leftKnee", p3: "leftAnkle" },
      goodRange: [165, 180], warningRange: [145, 165], criticalRange: [0, 145],
      side: "left", phase: "Bottom", weight: 5,
      cueGood: "Lifted leg extended straight behind", cueWarning: "Lifted leg bending — straighten for balance", cueCritical: "Lifted leg too bent — extend through the hip",
    },
    {
      id: "slrdl-hip-stability-l", name: "Hip Stability (Left Stance)",
      description: "The stance hip should remain stable without hiking or dropping during the movement.",
      angle: { joint: "leftHip", p1: "rightHip", p2: "leftHip", p3: "leftKnee" },
      goodRange: [80, 100], warningRange: [65, 80], criticalRange: [0, 65],
      side: "left", phase: "Hinge", weight: 6,
      cueGood: "Hip stable throughout", cueWarning: "Hip hiking — engage glute medius", cueCritical: "Significant hip instability — reduce range or use support",
    },
    {
      id: "slrdl-hip-stability-r", name: "Hip Stability (Right Stance)",
      description: "Hip stability for the right stance leg.",
      angle: { joint: "rightHip", p1: "leftHip", p2: "rightHip", p3: "rightKnee" },
      goodRange: [80, 100], warningRange: [65, 80], criticalRange: [0, 65],
      side: "right", phase: "Hinge", weight: 6,
      cueGood: "Hip stable throughout", cueWarning: "Hip hiking — engage glute medius", cueCritical: "Significant hip instability — reduce range or use support",
    },
  ],
  phases: [
    { name: "Setup", description: "Stand on one leg with a slight bend in the stance knee. The lifted leg trails slightly behind." },
    { name: "Hinge", description: "Push the hips back while keeping the spine neutral. The lifted leg rises behind as a counterbalance." },
    { name: "Bottom", description: "Maximum hip flexion with the torso near parallel and the lifted leg extended behind." },
    { name: "Return", description: "Drive the hips forward to return upright. Keep the lifted leg trailing until standing." },
  ],
};

const legDayExercises: ExerciseBiomechanics[] = [
  pistolSquat,
  romanianDeadlift,
  bulgarianSplitSquat,
  abductorMachine,
  sumoSquatAdductor,
  hipThrust,
  legExtension,
  cableKickback,
  hamstringCurl,
  wallSit,
  singleLegRDL,
];

export default legDayExercises;
